# Generated by Django 5.2.4 on 2025-09-04 10:58

import tarfile
import zipfile
import django.core.validators
import django.db.models.deletion
from django.core.exceptions import ValidationError
from django.conf import settings
from django.db import migrations, models


def scan_upload_path(instance, filename):
    return f"scans/patient_{instance.patient_id}/raw/{filename}"


def normalized_scan_path(instance, filename):
    return f"scans/patient_{instance.patient_id}/normalized/{filename}"


def cbct_upload_path(instance, filename):
    return f"scans/patient_{instance.patient_id}/cbct/{filename}"


def validate_cbct_file(value):
    filename = value.name.lower()
    valid_extensions = [
        '.dcm', '.dicom',
        '.nii', '.nii.gz', '.gz',
        '.mha', '.mhd',
        '.nrrd', '.nhdr',
        '.zip', '.tar', '.tar.gz', '.tgz',
    ]
    has_valid_extension = any(filename.endswith(ext) for ext in valid_extensions)
    if filename == 'dicomdir' or filename.endswith('/dicomdir'):
        return
    if not has_valid_extension:
        raise ValidationError(
            'Unsupported file format. Supported formats: DICOM (.dcm, .zip, .tar), '
            'NIfTI (.nii, .nii.gz), MetaImage (.mha, .mhd), NRRD (.nrrd, .nhdr)'
        )
    if filename.endswith(('.zip', '.tar', '.tar.gz', '.tgz')):
        try:
            if filename.endswith('.zip'):
                with zipfile.ZipFile(value, 'r') as zf:
                    file_list = zf.namelist()
                    has_dicom = any(f.lower().endswith('.dcm') or f.lower() == 'dicomdir'
                                    for f in file_list)
                    if not has_dicom:
                        raise ValidationError('Archive must contain DICOM files')
            elif filename.endswith(('.tar', '.tar.gz', '.tgz')):
                mode = 'r:gz' if filename.endswith(('.tar.gz', '.tgz')) else 'r'
                with tarfile.open(fileobj=value, mode=mode) as tf:
                    file_list = tf.getnames()
                    has_dicom = any(f.lower().endswith('.dcm') or f.lower().endswith('/dicomdir')
                                    for f in file_list)
                    if not has_dicom:
                        raise ValidationError('Archive must contain DICOM files')
        except Exception as exc:
            raise ValidationError(f'Error reading archive file: {str(exc)}')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maxillo.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('upper_scan_raw', models.FileField(blank=True, null=True, upload_to=scan_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])])),
                ('lower_scan_raw', models.FileField(blank=True, null=True, upload_to=scan_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])])),
                ('upper_scan_norm', models.FileField(blank=True, null=True, upload_to=normalized_scan_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])])),
                ('lower_scan_norm', models.FileField(blank=True, null=True, upload_to=normalized_scan_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl'])])),
                ('cbct', models.FileField(blank=True, null=True, upload_to=cbct_upload_path, validators=[validate_cbct_file])),
                ('ios_processing_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='not_uploaded', help_text='Processing status for intra-oral scans (upper and lower)', max_length=20)),
                ('cbct_processing_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='not_uploaded', help_text='Processing status for CBCT scan', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='maxillo.dataset')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='maxillo.folder')),
                ('modalities', models.ManyToManyField(blank=True, help_text='Modalities available for this patient', related_name='patients', to='common.modality')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='common.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(choices=[('manual', 'Manual'), ('pipeline', 'Pipeline')], max_length=10)),
                ('sagittal_left', models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10)),
                ('sagittal_right', models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10)),
                ('vertical', models.CharField(choices=[('Unknown', 'Unknown'), ('normal', 'Normal'), ('deep', 'Deep Bite'), ('reverse', 'Reverse Bite'), ('open', 'Open Bite')], max_length=10)),
                ('transverse', models.CharField(choices=[('Unknown', 'Unknown'), ('normal', 'Normal'), ('cross', 'Cross Bite'), ('scissor', 'Scissor Bite')], max_length=10)),
                ('midline', models.CharField(choices=[('Unknown', 'Unknown'), ('centered', 'Centered'), ('deviated', 'Deviated')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='maxillo.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='scans_tag_name_d48e7d_idx')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='maxillo.tag'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('admin', 'Administrator'), ('student_dev', 'Student Developer')], default='standard', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('ios', 'Intra-Oral Scans'), ('cbct', 'CBCT')], default='ios', help_text='Whether this caption describes IOS or CBCT scans', max_length=10)),
                ('duration', models.FloatField(help_text='Duration of audio recording in seconds')),
                ('text_caption', models.TextField(blank=True, help_text='Transcribed text from audio', null=True)),
                ('original_text_caption', models.TextField(blank=True, help_text='Original transcription before any edits', null=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Whether the transcription has been manually edited')),
                ('edit_history', models.JSONField(blank=True, default=list, help_text='History of edits with timestamps and users')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of speech-to-text processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='maxillo.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='scans_folde_parent__9b2827_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='scans_folde_name_7a86ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['patient', 'classifier'], name='scans_class_patient_c507dc_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['classifier'], name='scans_class_classif_fc1966_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project'], name='scans_patie_project_18f4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility'], name='scans_patie_visibil_a7bf65_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['uploaded_at'], name='scans_patie_uploade_2e9c22_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder'], name='scans_patie_folder__c2aeae_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='scans_patie_name_ca8447_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project', 'visibility'], name='scans_patie_project_84fea6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project', 'uploaded_at'], name='scans_patie_project_427bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='scans_patie_visibil_926fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder', 'visibility'], name='scans_patie_folder__b4f37a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project', 'folder', 'visibility'], name='scans_patie_project_3e6f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['patient', 'processing_status'], name='scans_voice_patient_a95f98_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='scans_voice_process_cea49d_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='scans_voice_user_id_d7afd5_idx'),
        ),
    ]
