# Generated by Django 5.2.4 on 2026-04-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0017_intraoral_segmentation_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cbct',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cbct_processing_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ios_processing_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lower_scan_norm',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lower_scan_raw',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='upper_scan_norm',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='upper_scan_raw',
        ),
    ]
