# Generated by Django 5.2.4 on 2026-05-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0018_remove_patient_cbct_and_more'),
        ('maxillo', '0019_rename_maxillo_fol_folder__e922d8_idx_maxillo_fol_folder__5d4ea1_idx_and_more'),
    ]

    operations = [
    ]
