# Generated by Django 5.2.15 on 2026-08-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_project_disabled_steps'),
        ('maxillo', '0026_folders_to_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxilloProject',
            fields=[
            ],
            options={
                'verbose_name': 'Maxillo project',
                'verbose_name_plural': 'Maxillo projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.project',),
        ),
    ]
