# Generated by Django 5.2.15 on 2026-09-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxillo', '0029_patient_project_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='sagittal_left',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II', 'Class II'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='sagittal_right',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II', 'Class II'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10),
        ),
    ]
