# Generated by Django 5.2.4 on 2025-09-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('maxillo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_slug', models.CharField(help_text='Slug for modality (e.g., cbct, ios, audio, bite_classification)', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dependency', 'Waiting for Dependencies'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher values = higher priority')),
                ('input_file_path', models.CharField(blank=True, help_text='Primary input object key', max_length=500)),
                ('output_files', models.JSONField(blank=True, default=dict, help_text='Dict of output file paths and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_logs', models.TextField(blank=True, help_text='Error logs if processing failed')),
                ('worker_id', models.CharField(blank=True, help_text='ID of worker processing this job', max_length=100)),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Jobs that must complete before this job can start', related_name='dependent_jobs', to='common.job')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='maxillo.patient')),
                ('voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='maxillo.voicecaption')),
            ],
            options={
                'db_table': 'scans_job',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='fileregistry',
            name='processing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='common.job'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['modality_slug', 'status'], name='scans_job_modalit_f8675b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='scans_job_status_7dcbd0_idx'),
        ),
    ]
