# Generated by Django 5.2.4 on 2026-06-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_add_brain_segmentation_file_types'),
        ('common', '0026_add_intraoral_photo_processed_type'),
    ]

    operations = [
    ]
