# Generated by Django 5.2.4 on 2026-06-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_merge_20260609_1701'),
        ('common', '0027_merge_laparoscopy_branch'),
    ]

    operations = [
    ]
