# Generated by Django 5.2.4 on 2026-06-22 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_alter_fileregistry_file_type_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='project_slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'project_slug', '-last_seen_at'], name='common_user_user_id_05dfbe_idx'),
        ),
    ]
