# Generated by Django 5.2.4 on 2026-07-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_usersession_project_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warn', 'Warning'), ('fail', 'Failed')], max_length=10)),
                ('ran_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
