# Generated by Django 5.2.15 on 2026-07-06 13:15

import django.db.models.deletion
from django.db import migrations, models


def seed_steps(apps, schema_editor):
    """Create one default ProcessingStep per existing ModalityProcessingConfig,
    reproducing today's behavior: slug == modality slug (the root step), copying
    queue/blocking, folding requires_processing into is_enabled, and translating
    the config's modality->modality depends_on into step->step edges."""
    ModalityProcessingConfig = apps.get_model('common', 'ModalityProcessingConfig')
    ProcessingStep = apps.get_model('common', 'ProcessingStep')

    step_by_modality = {}
    for cfg in ModalityProcessingConfig.objects.select_related('modality').all():
        modality = cfg.modality
        if modality is None:
            continue
        step = ProcessingStep.objects.create(
            modality=modality,
            name=modality.name,
            slug=modality.slug,
            queue_name=cfg.queue_name or '',
            is_blocking=cfg.is_blocking,
            is_enabled=bool(cfg.is_enabled and cfg.requires_processing),
            order=0,
        )
        step_by_modality[modality.id] = step

    for cfg in ModalityProcessingConfig.objects.prefetch_related('depends_on').all():
        step = step_by_modality.get(cfg.modality_id)
        if step is None:
            continue
        for dep_modality in cfg.depends_on.all():
            dep_step = step_by_modality.get(dep_modality.id)
            if dep_step is not None:
                step.depends_on.add(dep_step)

    # Reproduce the historical hardcoded ios -> bite_classification dependency
    # (formerly _LEGACY_DEPENDENTS) as a declarative downstream step of the ios
    # modality. bite_classification has never been a catalog Modality; it is a
    # derived stage of the ios pipeline, so it becomes a second ios step whose
    # slug is its own runner routing key. Admins can toggle/remove it going
    # forward.
    ios_root = ProcessingStep.objects.filter(slug='ios').first()
    if ios_root is not None and not ProcessingStep.objects.filter(slug='bite_classification').exists():
        bite = ProcessingStep.objects.create(
            modality=ios_root.modality,
            name='Bite classification',
            slug='bite_classification',
            queue_name='',
            is_blocking=False,
            is_enabled=ios_root.is_enabled,
            order=1,
        )
        bite.depends_on.add(ios_root)


def unseed_steps(apps, schema_editor):
    """Best-effort reverse: rebuild one ModalityProcessingConfig per root step
    (slug == modality slug), then drop all steps."""
    ModalityProcessingConfig = apps.get_model('common', 'ModalityProcessingConfig')
    ProcessingStep = apps.get_model('common', 'ProcessingStep')

    for step in ProcessingStep.objects.select_related('modality').all():
        if step.modality is None or step.slug != step.modality.slug:
            continue
        cfg, _ = ModalityProcessingConfig.objects.get_or_create(modality=step.modality)
        cfg.queue_name = step.queue_name
        cfg.is_blocking = step.is_blocking
        cfg.is_enabled = step.is_enabled
        cfg.requires_processing = step.is_enabled
        cfg.save()

    for step in ProcessingStep.objects.prefetch_related('depends_on').select_related('modality').all():
        cfg = ModalityProcessingConfig.objects.filter(modality=step.modality).first()
        if cfg is None:
            continue
        for dep in step.depends_on.all():
            if dep.modality_id:
                cfg.depends_on.add(dep.modality)

    ProcessingStep.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_seed_modality_processing_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('queue_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_blocking', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='common.processingstep')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='common.modality')),
            ],
            options={
                'ordering': ['modality__name', 'order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='common.processingstep'),
        ),
        # Seed steps from the config rows BEFORE the config model is deleted.
        migrations.RunPython(seed_steps, unseed_steps),
        migrations.DeleteModel(
            name='ModalityProcessingConfig',
        ),
    ]
