# Generated by Django 5.2.15 on 2026-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_processingstep_job_step_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingstep',
            options={'ordering': ['modality__name', 'slug']},
        ),
        migrations.RemoveField(
            model_name='processingstep',
            name='order',
        ),
        migrations.AddField(
            model_name='processingstep',
            name='discard_raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processingstep',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text="Steps whose output feeds this step's input. Declaring an input automatically makes this step wait for it to complete.", related_name='dependents', to='common.processingstep', verbose_name='Inputs'),
        ),
    ]
