# Generated by Django 5.2.15 on 2026-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_create_demo_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slurm_job_id',
            field=models.CharField(blank=True, default='', help_text='SLURM job id set by the runner worker', max_length=32),
        ),
        migrations.AddField(
            model_name='processingstep',
            name='algo_name',
            field=models.CharField(blank=True, default='', help_text="Exact algo directory name under ALGO_BASE_DIR on the cluster (e.g. 'sn' -> ALGO_BASE_DIR/sn/run.sbatch). Non-blank routes this step to SLURM-over-SSH dispatch instead of Celery.", max_length=200),
        ),
    ]
