# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0039_sitemaintenance_and_ios_landmark_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingstep",
            name="prefer_processed_for_viewer",
            field=models.BooleanField(
                default=False,
                help_text="Prefer a complete processed file set in the modality viewer, falling back to raw files when processed files are unavailable.",
            ),
        ),
    ]
