# Generated by Django 5.2.15 on 2026-08-06 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_retire_audio_transcription_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['domain', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('annotator', 'Annotator'), ('admin', 'Administrator')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectaccess',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('annotator', 'Annotator'), ('admin', 'Administrator')], default='viewer', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('domain', 'name')},
        ),
        migrations.CreateModel(
            name='AnnotationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(blank=True, choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy')], default='', help_text='Leave blank for a method available in every domain.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='annotation_methods',
            field=models.ManyToManyField(blank=True, related_name='projects', to='common.annotationmethod'),
        ),
    ]
