# Generated by Django 5.2.15 on 2026-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_backfill_project_domain_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disabled_steps',
            field=models.ManyToManyField(blank=True, related_name='disabled_for_projects', to='common.processingstep'),
        ),
    ]
