# Generated by Django 5.2.15 on 2026-08-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_cleanup_annotation_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=64, unique=True)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=64)),
                ('frame_of_reference_uid', models.CharField(blank=True, help_text='Coordinates are only comparable within one of these. Mirrors annotations.SourceResource.frame_of_reference_uid, which is what an annotation on this series actually anchors to.', max_length=64)),
                ('dicom_modality', models.CharField(blank=True, max_length=16)),
                ('sop_class_uid', models.CharField(blank=True, max_length=64)),
                ('transfer_syntax_uid', models.CharField(blank=True, max_length=64)),
                ('instance_count', models.PositiveIntegerField(default=0)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('columns', models.PositiveIntegerField(default=0)),
                ('deid_profile', models.CharField(blank=True, help_text='Which de-identification produced the stored bytes.', max_length=60)),
                ('deid_confidence', models.CharField(blank=True, help_text="What the de-identification actually established. 'header_only' means the pixels were never examined; nothing may present that to a user as 'de-identified'.", max_length=32)),
                ('sealed_at', models.DateTimeField(blank=True, help_text='Set once annotation work exists on this series. After it, no instance may be rewritten -- the lock guards FileRegistry rows and cannot see inside one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(help_text="The prefix row whose file_path is this series' object-storage prefix.", on_delete=django.db.models.deletion.CASCADE, related_name='dicom_series', to='common.fileregistry')),
            ],
            options={
                'verbose_name_plural': 'DICOM series',
            },
        ),
        migrations.CreateModel(
            name='DicomInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=64, unique=True)),
                ('instance_number', models.IntegerField(default=0)),
                ('object_key', models.CharField(help_text='Object-storage key of this instance, under the series prefix.', max_length=500, unique=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('frame_count', models.PositiveIntegerField(default=1)),
                ('image_position_patient', models.JSONField(blank=True, default=list)),
                ('image_orientation_patient', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='common.dicomseries')),
            ],
            options={
                'ordering': ['instance_number', 'sop_instance_uid'],
            },
        ),
        migrations.AddIndex(
            model_name='dicomseries',
            index=models.Index(fields=['study_instance_uid', 'series_instance_uid'], name='common_dico_study_i_cfd25c_idx'),
        ),
        migrations.AddIndex(
            model_name='dicominstance',
            index=models.Index(fields=['series', 'instance_number'], name='common_dico_series__e64783_idx'),
        ),
    ]
