# Generated by Django 5.2.15 on 2026-08-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0047_alter_fileregistry_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='domain',
            field=models.CharField(blank=True, choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy')], default='', help_text='Leave blank for a modality available in every domain.', max_length=20),
        ),
    ]
