# Generated by Django 5.2.15 on 2026-09-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_demo_guest_project_access'),
        ('common', '0056_alter_fileregistry_file_type'),
    ]

    operations = [
    ]
