# Generated by Django 5.2.15 on 2026-09-22 15:58

import common.external_services
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_merge_20260920_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable identifier used in code, e.g. "whisper_live".', max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=common.external_services.kind_choices, help_text='Decides which URL schemes and parameters are valid.', max_length=30)),
                ('base_url', models.CharField(help_text='e.g. ws://whisper:9097/ws or https://openrouter.ai/api/v1', max_length=500)),
                ('api_key_env', models.CharField(blank=True, help_text='NAME of the environment variable holding the key — never the key itself. The value is read from the environment at call time and is never stored, logged or shown here.', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='Model identifier, e.g. nvidia/nemotron-3-super-120b-a12b:free', max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Tuning for this kind. Unknown keys are refused when saving.')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Language codes this service accepts. Empty means the code default.')),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('connect_timeout_seconds', models.PositiveIntegerField(default=10)),
                ('ca_cert_path', models.CharField(blank=True, help_text='Pinned CA, for a wss:// or https:// endpoint with a self-signed certificate. Ignored for plain ws:// and http://.', max_length=500)),
                ('is_enabled', models.BooleanField(default=True, help_text='Unticking this turns the service off completely: it does NOT fall back to the environment.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External service',
                'ordering': ['kind', 'name'],
            },
        ),
    ]
