# Generated by Django 5.2.15 on 2026-09-22 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_externalservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], max_length=20)),
                ('modality_slug', models.CharField(blank=True, default='', help_text='Modality this applies to. Leave empty for every modality of the domain.', max_length=60)),
                ('project_key', models.CharField(default='', editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome classes for the section header, e.g. "fas fa-magnet me-1".', max_length=60)),
                ('subtitle_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_it', models.CharField(blank=True, max_length=200)),
                ('subtitle_de', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('active_slot', models.CharField(blank=True, editable=False, max_length=1, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Leave empty for the domain-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='common.project')),
            ],
            options={
                'ordering': ['domain', 'modality_slug', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier a structured report is filed under, and the section heading the model is asked to emit. Renaming it orphans that section of every report already produced.', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label_en', models.CharField(max_length=200)),
                ('label_it', models.CharField(blank=True, max_length=200)),
                ('label_de', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_it', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False, help_text='Marks the field as expected; it never blocks saving a caption.')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='common.reporttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('domain', 'modality_slug', 'project_key', 'active_slot'), name='one_active_report_template_per_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplatefield',
            unique_together={('template', 'key')},
        ),
    ]
