# Generated by Django 5.2.17 on 2026-09-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0023_remove_folder_is_demo'),
        ('cardiology', '0001_initial'),
        ('common', '0058_expire_legacy_share_links'),
        ('laparoscopy', '0015_remove_folder_is_demo'),
        ('maxillo', '0033_remove_folder_is_demo'),
        ('urology', '0003_remove_patient_dataset_remove_folder_is_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileregistry',
            name='cardiology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cardiology.patient'),
        ),
        migrations.AddField(
            model_name='fileregistry',
            name='cardiology_voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cardiology.voicecaption'),
        ),
        migrations.AddField(
            model_name='job',
            name='cardiology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cardiology.patient'),
        ),
        migrations.AddField(
            model_name='job',
            name='cardiology_voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cardiology.voicecaption'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='cardiology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='cardiology.patient'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='cardiology_voice_caption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='cardiology.voicecaption'),
        ),
        migrations.AlterField(
            model_name='annotationmethod',
            name='domain',
            field=models.CharField(blank=True, choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='', help_text='Leave blank for a method available in every domain.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileregistry',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileregistry',
            name='file_type',
            field=models.CharField(choices=[('cbct_raw', 'CBCT Raw'), ('cbct_processed', 'CBCT Processed'), ('ios_raw_upper', 'IOS Raw Upper'), ('ios_raw_lower', 'IOS Raw Lower'), ('ios_processed_upper', 'IOS Processed Upper'), ('ios_processed_lower', 'IOS Processed Lower'), ('ios_landmarks', 'IOS Landmarks'), ('ios_landmarks_prediction', 'IOS Landmark Prediction'), ('audio_raw', 'Audio Raw'), ('audio_processed', 'Audio Processed Text'), ('bite_classification', 'Bite Classification Results'), ('rgb_image', 'RGB Image'), ('volume_raw', 'Volume Raw'), ('volume_processed', 'Volume Processed'), ('image_raw', 'Image Raw'), ('image_processed', 'Image Processed'), ('generic_raw', 'Generic Raw'), ('generic_processed', 'Generic Processed'), ('braintumor_mri_t1_raw', 'Brain MRI T1 Raw'), ('braintumor_mri_t1_processed', 'Brain MRI T1 Processed'), ('braintumor_mri_t1c_raw', 'Brain MRI T1c Raw'), ('braintumor_mri_t1c_processed', 'Brain MRI T1c Processed'), ('braintumor_mri_t2_raw', 'Brain MRI T2 Raw'), ('braintumor_mri_t2_processed', 'Brain MRI T2 Processed'), ('braintumor_mri_flair_raw', 'Brain MRI FLAIR Raw'), ('braintumor_mri_flair_processed', 'Brain MRI FLAIR Processed'), ('braintumor_mri_seg_raw', 'Brain MRI Segmentation Raw'), ('braintumor_mri_seg_processed', 'Brain MRI Segmentation Processed'), ('intraoral_raw', 'Intraoral Photographs Raw'), ('intraoral_processed', 'Intraoral Photographs Processed'), ('intraoral-photo_processed', 'Intraoral Photo Processed'), ('teleradiography_raw', 'Teleradiography Raw'), ('teleradiography_processed', 'Teleradiography Processed'), ('panoramic_raw', 'panoramic Raw'), ('panoramic_processed', 'panoramic Processed'), ('video_raw', 'Video Raw'), ('video_processed', 'Video Processed'), ('urology_mri_raw', 'Urology MRI Raw'), ('urology_mri_processed', 'Urology MRI Processed'), ('urology_wsi_raw', 'Urology WSI Raw'), ('urology_wsi_processed', 'Urology WSI Processed'), ('urology_confocal_raw', 'Urology Confocale Raw'), ('urology_confocal_processed', 'Urology Confocale Processed'), ('urology_segmentation', 'Urology Segmentation (GeoJSON)'), ('ecg_raw', 'ECG Raw'), ('ecg_processed', 'ECG Plot (browser-generated)'), ('annotation_mask', 'Annotation Mask')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='modality',
            name='domain',
            field=models.CharField(blank=True, choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='', help_text='Leave blank for a modality available in every domain.', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='maxillo', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='maxillo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fileregistry',
            index=models.Index(fields=['domain', 'file_type', 'cardiology_patient'], name='maxillo_fil_domain_382c62_idx'),
        ),
    ]
