# Generated by Django 5.2.15 on 2026-09-22 16:26

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0023_remove_folder_is_demo'),
        ('common', '0059_reporttemplate_reporttemplatefield_and_more'),
        ('laparoscopy', '0015_remove_folder_is_demo'),
        ('maxillo', '0033_remove_folder_is_demo'),
        ('urology', '0003_remove_patient_dataset_remove_folder_is_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('system_prompt', models.TextField(help_text='The instruction. A fixed output contract is appended by the code.')),
                ('user_template', models.TextField(help_text='The message itself. Placeholders: {language}, {source_language}, {fields}, {caption}. Literal braces must be doubled: {{ and }}.')),
                ('version', models.PositiveIntegerField(default=1, editable=False, help_text='Bumped whenever the wording changes; recorded on every report.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology')], max_length=20)),
                ('task_slug', models.CharField(default='caption_to_template', max_length=60)),
                ('generation_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('template_snapshot', models.JSONField(blank=True, default=list)),
                ('source_text', models.TextField(help_text='The caption text this was produced from, as it was at the time.')),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_language', models.CharField(blank=True, help_text='The language it was dictated in.', max_length=5)),
                ('report_language', models.CharField(default='it', help_text='The language it was written in.', max_length=5)),
                ('structured', models.JSONField(blank=True, default=dict, help_text='{field key: text}, the canonical form.')),
                ('structured_text', models.TextField(blank=True, help_text='The rendered, readable form.')),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('prompt_version', models.PositiveIntegerField(default=0)),
                ('prompt_rendered', models.TextField(blank=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brain_voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='brain.voicecaption')),
                ('laparoscopy_voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='laparoscopy.voicecaption')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caption_reports', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caption_reports', to='common.externalservice')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='common.reporttemplate')),
                ('urology_voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='urology.voicecaption')),
                ('voice_caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='maxillo.voicecaption')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caption_reports', to='common.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['domain', 'task_slug', '-created_at'], name='common_capt_domain_342c08_idx'), models.Index(fields=['status', 'created_at'], name='common_capt_status_3894b9_idx')],
            },
            bases=(common.models.DomainFKAccessorMixin, models.Model),
        ),
    ]
