# Generated by Django 5.2.17 on 2026-09-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_fileregistry_cardiology_patient_and_more'),
        ('common', '0061_report_structuring_method'),
    ]

    operations = [
    ]
