# Generated by Django 5.2.17 on 2026-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_merge_20260925_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionreport',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], max_length=20),
        ),
    ]
