# Generated by Django 5.2.4 on 2026-03-31 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def brain_scan_upload_path(instance, filename):
    return f"brain/patient_{instance.patient_id}/raw/{filename}"


def brain_normalized_scan_path(instance, filename):
    return f"brain/patient_{instance.patient_id}/normalized/{filename}"


def brain_cbct_upload_path(instance, filename):
    return f"brain/patient_{instance.patient_id}/cbct/{filename}"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0003_delete_brainuserprofile'),
        ('common', '0020_invitation_projects_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_datasets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brain_dataset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_folders_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='brain.folder')),
            ],
            options={
                'db_table': 'brain_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('upper_scan_raw', models.FileField(blank=True, null=True, upload_to=brain_scan_upload_path)),
                ('lower_scan_raw', models.FileField(blank=True, null=True, upload_to=brain_scan_upload_path)),
                ('upper_scan_norm', models.FileField(blank=True, null=True, upload_to=brain_normalized_scan_path)),
                ('lower_scan_norm', models.FileField(blank=True, null=True, upload_to=brain_normalized_scan_path)),
                ('cbct', models.FileField(blank=True, null=True, upload_to=brain_cbct_upload_path)),
                ('ios_processing_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='not_uploaded', help_text='Processing status for intra-oral scans (upper and lower)', max_length=20)),
                ('cbct_processing_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='not_uploaded', help_text='Processing status for CBCT scan', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='brain.dataset')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='brain.folder')),
                ('modalities', models.ManyToManyField(blank=True, help_text='Modalities available for this patient', related_name='brain_patients', to='common.modality')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_patients_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brain_patient',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(choices=[('manual', 'Manual'), ('pipeline', 'Pipeline')], max_length=10)),
                ('sagittal_left', models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10)),
                ('sagittal_right', models.CharField(choices=[('Unknown', 'Unknown'), ('I', 'Class I'), ('II_edge', 'Class II Edge'), ('II_full', 'Class II Full'), ('III', 'Class III')], max_length=10)),
                ('vertical', models.CharField(choices=[('Unknown', 'Unknown'), ('normal', 'Normal'), ('deep', 'Deep Bite'), ('reverse', 'Reverse Bite'), ('open', 'Open Bite')], max_length=10)),
                ('transverse', models.CharField(choices=[('Unknown', 'Unknown'), ('normal', 'Normal'), ('cross', 'Cross Bite'), ('scissor', 'Scissor Bite')], max_length=10)),
                ('midline', models.CharField(choices=[('Unknown', 'Unknown'), ('centered', 'Centered'), ('deviated', 'Deviated')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_classifications_authored', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='brain.patient')),
            ],
            options={
                'db_table': 'brain_classification',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brain_tag',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='brain_tag_name_63af86_idx')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='brain.tag'),
        ),
        migrations.CreateModel(
            name='VoiceCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(default='ios', max_length=255)),
                ('duration', models.FloatField(help_text='Duration of audio recording in seconds')),
                ('text_caption', models.TextField(blank=True, null=True)),
                ('original_text_caption', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='brain.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_voice_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brain_voicecaption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query_params', models.JSONField(default=dict)),
                ('query_summary', models.CharField(blank=True, max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('patient_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brain_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='brain_expor_user_id_26524a_idx'), models.Index(fields=['status', 'created_at'], name='brain_expor_status_368e70_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='brain_folde_parent__0160a8_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='brain_folde_name_194da1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['patient', 'classifier'], name='brain_class_patient_4d4afa_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['classifier'], name='brain_class_classif_fa5352_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility'], name='brain_patie_visibil_218edd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['uploaded_at'], name='brain_patie_uploade_2a8976_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder'], name='brain_patie_folder__37cf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='brain_patie_name_2b9f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='brain_patie_visibil_2b8628_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder', 'visibility'], name='brain_patie_folder__1cd6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['patient', 'processing_status'], name='brain_voice_patient_193cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='brain_voice_process_173473_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='brain_voice_user_id_f50a00_idx'),
        ),
    ]
