# Generated by Django 5.2.4 on 2026-05-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_remove_patient_cbct_and_more'),
        ('brain', '0010_rename_brain_folde_folder__7178b6_idx_brain_folde_folder__0ad931_idx_and_more'),
    ]

    operations = [
    ]
