# Generated by Django 5.2.4 on 2026-07-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0015_delete_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Share link expiry; null = never expires', null=True),
        ),
    ]
