# Generated by Django 5.2.15 on 2026-08-06 09:31 (hand-edited: data migration
# inserted before the Patient.folders M2M removal so the through table can be
# read while it still exists).

import django.db.models.deletion
from django.conf import settings
from django.utils.text import slugify
from django.db import migrations, models

DOMAIN = "brain"

ROLE_MAP = {"standard": "viewer", "annotator": "annotator", "project_manager": "admin"}
ROLE_RANK = {"viewer": 0, "annotator": 1, "admin": 2}


def _unique_slug(Project, base):
    slug = slugify(base) or DOMAIN
    candidate, i = slug, 2
    while Project.objects.filter(slug=candidate).exists():
        candidate = f"{slug}-{i}"
        i += 1
    return candidate


def _unique_project_name(Project, base):
    name, i = base, 2
    while Project.objects.filter(domain=DOMAIN, name=name).exists():
        name = f"{base} {i}"
        i += 1
    return name


def _unique_folder_name(Folder, project, base):
    name, i = base, 2
    while Folder.objects.filter(project=project, parent__isnull=True, name=name).exists():
        name = f"{base} ({i})"
        i += 1
    return name


def _grant(ProjectAccess, user_id, project, role):
    existing = ProjectAccess.objects.filter(user_id=user_id, project=project).first()
    new_rank = ROLE_RANK.get(role, 0)
    if existing is None:
        ProjectAccess.objects.create(user_id=user_id, project=project, role=role)
    elif ROLE_RANK.get(existing.role, 0) < new_rank:
        existing.role = role
        existing.save(update_fields=["role"])


def migrate_folders_to_projects(apps, schema_editor):
    Project = apps.get_model("common", "Project")
    ProjectAccess = apps.get_model("common", "ProjectAccess")
    AnnotationMethod = apps.get_model("common", "AnnotationMethod")
    Folder = apps.get_model("brain", "Folder")
    Patient = apps.get_model("brain", "Patient")
    FolderAccess = apps.get_model("brain", "FolderAccess")

    catchall = Project.objects.filter(slug=DOMAIN).first()
    if catchall is None:
        catchall = Project.objects.create(name=DOMAIN.title(), slug=DOMAIN, domain=DOMAIN)
    if not catchall.domain:
        catchall.domain = DOMAIN
        catchall.save(update_fields=["domain"])

    domain_methods = AnnotationMethod.objects.filter(domain=DOMAIN)
    common_methods = AnnotationMethod.objects.filter(domain="")

    # folder id -> migrated folder row (project assigned).
    folder_map = {}

    for root in Folder.objects.filter(parent__isnull=True).order_by("id"):
        project = Project.objects.create(
            name=_unique_project_name(Project, root.name or "Project"),
            slug=_unique_slug(Project, root.name or DOMAIN),
            domain=DOMAIN,
            created_by=root.created_by,
        )
        project.modalities.set(catchall.modalities.all())
        project.annotation_methods.set(domain_methods | common_methods)

        root.project = project
        root.save(update_fields=["project"])
        folder_map[root.id] = root

        queue = list(Folder.objects.filter(parent=root).order_by("id"))
        while queue:
            old = queue.pop(0)
            new = Folder.objects.create(
                name=_unique_folder_name(Folder, project, old.name or "Folder"),
                parent=None,
                project=project,
                created_by=old.created_by,
                is_demo=old.is_demo,
            )
            folder_map[old.id] = new
            queue.extend(Folder.objects.filter(parent=old).order_by("id"))

    # Delete dead subfolder rows (their FolderAccess folds into projects below;
    # patients get repointed to the mapped rows first). Root rows are kept
    # (they become the project's default folder), so any mapped row whose id
    # differs from its old id is a freshly created flattened folder.
    dead_old_ids = [old_id for old_id, new in folder_map.items() if new.id != old_id]

    # Fold every FolderAccess row into ProjectAccess BEFORE deleting the old
    # subfolder rows (their FolderAccess rows cascade away on delete).
    for access in FolderAccess.objects.select_related("folder").all():
        _grant(ProjectAccess, access.user_id, access.folder.project, ROLE_MAP.get(access.role, "viewer"))

    Folder.objects.filter(id__in=dead_old_ids).delete()

    # Patients: first folder (by id) wins; no folders -> catch-all project.
    default_folder = Folder.objects.filter(project=catchall, parent__isnull=True).first()
    if default_folder is None:
        default_folder = Folder.objects.create(name="General", parent=None, project=catchall)

    for patient in Patient.objects.all():
        first_fid = patient.folders.order_by("id").values_list("id", flat=True).first()
        if first_fid and first_fid in folder_map:
            patient.project = folder_map[first_fid].project
            patient.folder = folder_map[first_fid]
        else:
            patient.project = catchall
            patient.folder = default_folder
        patient.save(update_fields=["project", "folder"])

    for folder in Folder.objects.filter(project__isnull=True):
        folder.project = catchall
        folder.save(update_fields=["project"])

    for access in FolderAccess.objects.select_related("folder").all():
        _grant(ProjectAccess, access.user_id, access.folder.project, ROLE_MAP.get(access.role, "viewer"))


class Migration(migrations.Migration):

    dependencies = [
        ("brain", "0017_folder_is_demo"),
        ("common", "0043_backfill_project_domain_and_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="folder",
            name="project",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="brain_folders", to="common.project"),
        ),
        migrations.AddField(
            model_name="patient",
            name="folder",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="patients", to="brain.folder"),
        ),
        migrations.AddField(
            model_name="patient",
            name="project",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="brain_patients", to="common.project"),
        ),
        migrations.RunPython(migrate_folders_to_projects, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="patient",
            name="folders",
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("project", "name", "parent")},
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["project"], name="brain_folde_project_70ad46_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["folder"], name="brain_patie_folder__37cf7a_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["project"], name="brain_patie_project_2d3fc6_idx"),
        ),
    ]
