# Generated by Django 5.2.15 on 2026-08-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0018_alter_folder_unique_together_remove_patient_folders_and_more'),
        ('common', '0044_project_disabled_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainProject',
            fields=[
            ],
            options={
                'verbose_name': 'Brain project',
                'verbose_name_plural': 'Brain projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.project',),
        ),
    ]
