"""
Django settings for yggdrasil project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json as _json
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _read_app_version() -> str:
    try:
        return (BASE_DIR / "VERSION").read_text(encoding="utf-8").strip()
    except OSError:
        # A missing VERSION file must never prevent the app from booting.
        return "0.0.0-dev"


APP_VERSION = _read_app_version()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY: No default secret key - must be provided via environment variable
SECRET_KEY = config("SECRET_KEY", default=None)
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable must be set for security reasons")

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY: Debug disabled by default for security
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=str).split(
    ","
)

# Environment-aware SSL settings
ENABLE_SSL = config("ENABLE_SSL", default=False, cast=bool)
ENABLE_HTTPS_REDIRECT = config("ENABLE_HTTPS_REDIRECT", default=False, cast=bool)
FORCE_HTTPS = config("FORCE_HTTPS", default=False, cast=bool)

# Disable HTTPS redirect in development (DEBUG mode)
# HTTPS can be handled by reverse proxy (e.g., nginx) via proxy-net
if ENABLE_SSL and not DEBUG:
    # HTTPS settings - enforce HTTPS everywhere (production only)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = ENABLE_HTTPS_REDIRECT or FORCE_HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development mode: no HTTPS redirect, allow HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # Still set proxy header for reverse proxy scenarios, but don't enforce redirect
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "common",
    "annotations",
    "maxillo",
    "brain",
    "laparoscopy",
]

# Live Whisper is reached only by the ASGI WebSocket relay. The browser never
# receives the shared API token or connects to the self-signed upstream.
WHISPER_WS_URL = config(
    "WHISPER_WS_URL", default="wss://155.185.48.254:9097/ws"
)
WHISPER_API_TOKEN = config("WHISPER_API_TOKEN", default="")
WHISPER_CA_CERT = config(
    "WHISPER_CA_CERT", default=str(BASE_DIR / "certs" / "whisper-live.pem")
)
WHISPER_CONNECT_TIMEOUT = config("WHISPER_CONNECT_TIMEOUT", default=10, cast=int)

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "yggdrasil.middleware.RequestLoggingMiddleware",
    "yggdrasil.middleware.SiteMaintenanceMiddleware",
    "yggdrasil.middleware.ProjectSessionMiddleware",
    "yggdrasil.middleware.ActiveProfileMiddleware",
    "yggdrasil.middleware.DemoGuestReadOnlyMiddleware",
    "yggdrasil.middleware.PresenceMiddleware",
]

ROOT_URLCONF = "yggdrasil.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "common.context_processors.current_project",
                "common.context_processors.app_meta",
                "common.context_processors.site_maintenance",
                "common.context_processors.user_prefs",
            ],
        },
    },
]

WSGI_APPLICATION = "yggdrasil.wsgi.application"
ASGI_APPLICATION = "yggdrasil.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SECURITY: Database credentials must be provided via environment variables
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME", default=None),
        "USER": config("DB_USER", default=None),
        "PASSWORD": config("DB_PASSWORD", default=None),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="3306"),
        "OPTIONS": {},
    }
}

# FileRegistry.file_path is a unique CharField(max_length=500). MySQL 8 + utf8mb4 caps a
# unique index at 3072 bytes (768 chars), so 500 is safe; silence the conservative
# mysql.W003 warning so `migrate --check` stays clean.
SILENCED_SYSTEM_CHECKS = ["mysql.W003"]

# Validate required database credentials
if not DATABASES["default"]["NAME"]:
    raise ValueError("DB_NAME environment variable must be set")
if not DATABASES["default"]["USER"]:
    raise ValueError("DB_USER environment variable must be set")
if not DATABASES["default"]["PASSWORD"]:
    raise ValueError("DB_PASSWORD environment variable must be set")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise serves collected static files from gunicorn in production (DEBUG=False),
# since the external nginx-proxy forwards /static/* straight through to the app.
# Compressed (not manifest) storage: templates reference assets by literal path, so
# filenames must stay stable — manifest hashing would 404 those refs.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 1048576000 * 5  # 5GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1048576000 * 5  # 5GB
DATA_UPLOAD_MAX_NUMBER_FILES = 1500  # large DICOM folder uploads


if ENABLE_SSL:
    CORS_ALLOWED_ORIGINS = [
        "https://yggdrasil.ing.unimore.it",
        "https://localhost:8000",
        "https://127.0.0.1:8000",
    ]
else:
    CORS_ALLOWED_ORIGINS = config(
        "CORS_ALLOWED_ORIGINS",
        default="http://localhost:8000,http://127.0.0.1:8000",
        cast=str,
    ).split(",")

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://yggdrasil.ing.unimore.it,http://localhost:8000,http://127.0.0.1:8000",
    cast=str,
).split(",")

# SECURITY: Enhanced CSRF and Session Security
CSRF_USE_SESSIONS = True  # Store CSRF token in session for better security
CSRF_COOKIE_HTTPONLY = True  # Prevent XSS attacks on CSRF cookie
CSRF_COOKIE_SAMESITE = "Strict"  # Prevent CSRF attacks
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks on session cookie
SESSION_COOKIE_SAMESITE = "Strict"  # Prevent session fixation attacks

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login URLs
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Shared read-only "guest" account the public demo auto-logs-in as. It holds a
# standard ProjectAccess on every project but no FolderAccess, so it can only
# read is_demo folders (see common.permissions) and can never write (see
# yggdrasil.middleware.DemoGuestReadOnlyMiddleware).
DEMO_GUEST_USERNAME = config("DEMO_GUEST_USERNAME", default="guest")

# Email settings
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
EMAIL_SENDER_EMAILS = [
    email
    for email in (
        item.strip()
        for item in config("EMAIL_SENDER_EMAILS", default=DEFAULT_FROM_EMAIL).split(",")
    )
    if email
]
if DEFAULT_FROM_EMAIL and DEFAULT_FROM_EMAIL not in EMAIL_SENDER_EMAILS:
    EMAIL_SENDER_EMAILS.insert(0, DEFAULT_FROM_EMAIL)

# Object storage (S3-compatible, e.g. Garage)
OBJECT_STORAGE_ENDPOINT_URL = config(
    "OBJECT_STORAGE_ENDPOINT_URL", default="http://garage:3900"
)
OBJECT_STORAGE_REGION = config("OBJECT_STORAGE_REGION", default="")
OBJECT_STORAGE_ACCESS_KEY_ID = config(
    "OBJECT_STORAGE_ACCESS_KEY_ID", default="garage-access-key"
)
OBJECT_STORAGE_SECRET_ACCESS_KEY = config(
    "OBJECT_STORAGE_SECRET_ACCESS_KEY", default="garage-secret-key"
)
OBJECT_STORAGE_BUCKET = config("OBJECT_STORAGE_BUCKET", default="yggdrasil")
OBJECT_STORAGE_USE_SSL = config("OBJECT_STORAGE_USE_SSL", default=False, cast=bool)
OBJECT_STORAGE_VERIFY_SSL = config("OBJECT_STORAGE_VERIFY_SSL", default=True, cast=bool)
OBJECT_STORAGE_ADDRESSING_STYLE = config(
    "OBJECT_STORAGE_ADDRESSING_STYLE", default="path"
)
OBJECT_STORAGE_KEY_PREFIX = config("OBJECT_STORAGE_KEY_PREFIX", default="")

# Async jobs (distributed runners)
_REDIS_PASSWORD = config("REDIS_PASSWORD")
_REDIS_HOST = config("REDIS_HOST", default="redis")
_REDIS_PORT = config("REDIS_PORT", default=6379, cast=int)
_REDIS_BROKER_DB = config("REDIS_BROKER_DB", default=0, cast=int)
_REDIS_RESULT_DB = config("REDIS_RESULT_DB", default=1, cast=int)
REDIS_PRESENCE_DB = config("REDIS_PRESENCE_DB", default=2, cast=int)
_DEFAULT_REDIS_URL = f"redis://:{_REDIS_PASSWORD}@{_REDIS_HOST}:{_REDIS_PORT}"
REDIS_PRESENCE_URL = f"{_DEFAULT_REDIS_URL}/{REDIS_PRESENCE_DB}"
PRESENCE_TTL_SECONDS = config("PRESENCE_TTL_SECONDS", default=90, cast=int)
CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL",
    default=f"{_DEFAULT_REDIS_URL}/{_REDIS_BROKER_DB}",
)
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=f"{_DEFAULT_REDIS_URL}/{_REDIS_RESULT_DB}",
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = config("CELERY_TIMEZONE", default="UTC")

RUNNER_DEFAULT_QUEUE = config("RUNNER_DEFAULT_QUEUE", default="runner")
RUNNER_QUEUE_BY_MODALITY = _json.loads(config("RUNNER_QUEUE_BY_MODALITY", default="{}"))
if not isinstance(RUNNER_QUEUE_BY_MODALITY, dict):
    RUNNER_QUEUE_BY_MODALITY = {}
RUNNER_QUEUE_BY_PROJECT = _json.loads(config("RUNNER_QUEUE_BY_PROJECT", default="{}"))
if not isinstance(RUNNER_QUEUE_BY_PROJECT, dict):
    RUNNER_QUEUE_BY_PROJECT = {}
RUNNER_TASK_NAME = config("RUNNER_TASK_NAME", default="yggdrasil.runner.process_job")

# Maintenance queue: consumed ONLY by the local maintenance worker (compose
# service), never by external runners. A collision would let runners eat
# backup tasks, so fail hard at startup.
MAINTENANCE_QUEUE = config("MAINTENANCE_QUEUE", default="maintenance")
_runner_queues = {RUNNER_DEFAULT_QUEUE}
_runner_queues.update(str(q) for q in RUNNER_QUEUE_BY_MODALITY.values())
_runner_queues.update(str(q) for q in RUNNER_QUEUE_BY_PROJECT.values())
if MAINTENANCE_QUEUE in _runner_queues:
    raise ValueError(
        f"MAINTENANCE_QUEUE '{MAINTENANCE_QUEUE}' collides with a runner queue; "
        "external runners must never consume maintenance tasks."
    )

# Database backups (Phase 2): daily dump to object storage.
BACKUP_KEEP_DAILY = config("BACKUP_KEEP_DAILY", default=14, cast=int)
BACKUP_KEEP_WEEKLY = config("BACKUP_KEEP_WEEKLY", default=8, cast=int)
BACKUP_KEY_PREFIX = config("BACKUP_KEY_PREFIX", default="backups/mysql/")

from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "backup-database-daily": {
        "task": "common.tasks.backup_database",
        "schedule": crontab(hour=3, minute=0),
        "options": {"queue": MAINTENANCE_QUEUE},
    },
}


def _parse_runner_tokens(raw: str):
    raw = (raw or "").strip()
    if not raw:
        return set()

    if raw.startswith("{") or raw.startswith("["):
        try:
            parsed = _json.loads(raw)
            if isinstance(parsed, list):
                return {str(v).strip() for v in parsed if str(v).strip()}
            if isinstance(parsed, dict):
                vals = []
                for v in parsed.values():
                    if isinstance(v, list):
                        vals.extend(v)
                    else:
                        vals.append(v)
                return {str(v).strip() for v in vals if str(v).strip()}
        except Exception:
            pass

    return {tok.strip() for tok in raw.split(",") if tok.strip()}


RUNNER_API_TOKENS = _parse_runner_tokens(config("RUNNER_API_TOKENS", default=""))

# --- Runner worker (Yggdrasil 2.0) -----------------------------------------
# The web app never uses any of this — these settings are consumed only by the
# dedicated runner worker (docker-compose 'runner-worker', see common.runner). They
# live in a separate .env.worker layered over .env so the worker's SSH/cluster config
# stays out of the web container.
#
# SSH into the cluster login node (the worker is the ONLY holder of the key):
SLURM_SSH_HOST = config("SLURM_SSH_HOST", default="")
SLURM_SSH_PORT = config("SLURM_SSH_PORT", default=22, cast=int)
SLURM_SSH_USER = config("SLURM_SSH_USER", default="")
SLURM_SSH_KEY = config("SLURM_SSH_KEY", default="")  # path to the private key
SLURM_SSH_PASSWORD = config("SLURM_SSH_PASSWORD", default="")
# Directory on the cluster holding one subdir per algo, each with a run.sbatch
# (ProcessingStep.algo_name is resolved against this: ALGO_BASE_DIR/<algo_name>/run.sbatch).
ALGO_BASE_DIR = config("ALGO_BASE_DIR", default="")
# Shared-FS base where the worker stages each job's private workdir + creds.env.
SLURM_STAGE_DIR = config("SLURM_STAGE_DIR", default="")
# sacct polling cadence and the wall-clock ceiling before a job is declared stuck.
SLURM_POLL_INTERVAL = config("SLURM_POLL_INTERVAL", default=15, cast=int)
SLURM_MAX_WALL_SECONDS = config("SLURM_MAX_WALL_SECONDS", default=24 * 3600, cast=int)

# Worker -> web runner API (host-independent boundary). The runner worker is
# intentionally off app-net, so configure a public/routable API URL.
RUNNER_API_BASE_URL = config("RUNNER_API_BASE_URL", default="")
RUNNER_API_TOKEN = config("RUNNER_API_TOKEN", default="")  # one of RUNNER_API_TOKENS
RUNNER_WORKER_ID = config("RUNNER_WORKER_ID", default="slurm-runner")

CELERY_TASK_ROUTES = {
    RUNNER_TASK_NAME: {"queue": RUNNER_DEFAULT_QUEUE},
    "common.tasks.*": {"queue": MAINTENANCE_QUEUE},
}

# Logging Configuration
LOG_LEVEL = config("LOG_LEVEL", default="DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "detailed": {
            "format": "[{asctime}] {levelname} {name} {funcName}:{lineno} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "detailed",
            "level": LOG_LEVEL,
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "detailed",
            "level": LOG_LEVEL,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "maxillo": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "yggdrasil": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Add specific logger for the middleware
        "yggdrasil.middleware": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

# In production, ensure we capture all errors
if not DEBUG:
    LOGGING["loggers"]["django"]["level"] = "WARNING"
    LOGGING["loggers"]["django.request"]["level"] = "ERROR"
    LOGGING["loggers"]["django.server"]["level"] = "ERROR"
    # But keep our app logs at DEBUG level
    LOGGING["loggers"]["maxillo"]["level"] = "DEBUG"
    LOGGING["loggers"]["yggdrasil"]["level"] = "DEBUG"
    LOGGING["loggers"]["yggdrasil.middleware"]["level"] = "DEBUG"

os.makedirs(BASE_DIR / "logs", exist_ok=True)
