# Generated by Django 5.2.4 on 2026-05-04 09:08

import django.db.models.deletion
import laparoscopy.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0023_rename_common_file_domain_22309d_idx_maxillo_fil_domain_760eb4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laparoscopy_datasets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_dataset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laparoscopy_folders_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='laparoscopy.folder')),
            ],
            options={
                'db_table': 'laparoscopy_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('upper_scan_raw', models.FileField(blank=True, null=True, upload_to=laparoscopy.models.laparoscopy_scan_upload_path)),
                ('lower_scan_raw', models.FileField(blank=True, null=True, upload_to=laparoscopy.models.laparoscopy_scan_upload_path)),
                ('upper_scan_norm', models.FileField(blank=True, null=True, upload_to=laparoscopy.models.laparoscopy_normalized_scan_path)),
                ('lower_scan_norm', models.FileField(blank=True, null=True, upload_to=laparoscopy.models.laparoscopy_normalized_scan_path)),
                ('cbct', models.FileField(blank=True, null=True, upload_to=laparoscopy.models.laparoscopy_cbct_upload_path)),
                ('ios_processing_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='not_uploaded', help_text='Processing status for intra-oral scans (upper and lower)', max_length=20)),
                ('cbct_processing_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='not_uploaded', help_text='Processing status for CBCT scan', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='laparoscopy.dataset')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='laparoscopy.folder')),
                ('modalities', models.ManyToManyField(blank=True, help_text='Modalities available for this patient', related_name='laparoscopy_patients', to='common.modality')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laparoscopy_patients_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_patient',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(choices=[('manual', 'Manual'), ('pipeline', 'Pipeline')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laparoscopy_classifications_authored', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='laparoscopy.patient')),
            ],
            options={
                'db_table': 'laparoscopy_classification',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'laparoscopy_tag',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='laparoscopy_name_667528_idx')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='laparoscopy.tag'),
        ),
        migrations.CreateModel(
            name='VoiceCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.FloatField(help_text='Duration of audio recording in seconds')),
                ('text_caption', models.TextField(blank=True, null=True)),
                ('original_text_caption', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='laparoscopy.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_voice_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_voicecaption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='laparoscopy_parent__eabfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='laparoscopy_name_f7cfea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['patient', 'classifier'], name='laparoscopy_patient_fcac41_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['classifier'], name='laparoscopy_classif_24566b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility'], name='laparoscopy_visibil_bee2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['uploaded_at'], name='laparoscopy_uploade_9a3089_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder'], name='laparoscopy_folder__f9826a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='laparoscopy_name_f7349e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='laparoscopy_visibil_73d22a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder', 'visibility'], name='laparoscopy_folder__db1089_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['patient', 'processing_status'], name='laparoscopy_patient_74be01_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='laparoscopy_process_f264f0_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='laparoscopy_user_id_38a7e2_idx'),
        ),
    ]
