# Generated by Django 5.2.4 on 2026-05-05 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_fileregistry_laparoscopy_patient_and_more'),
        ('laparoscopy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadrantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#e74c3c', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_quadrant_types', to='common.project')),
            ],
            options={
                'db_table': 'laparoscopy_quadranttype',
                'ordering': ['order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_region_types', to='common.project')),
            ],
            options={
                'db_table': 'laparoscopy_regiontype',
                'ordering': ['order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QuadrantClassificationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_laparoscopy_quadrant_markers', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrant_markers', to='laparoscopy.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_laparoscopy_quadrant_markers', to=settings.AUTH_USER_MODEL)),
                ('quadrant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='laparoscopy.quadranttype')),
            ],
            options={
                'db_table': 'laparoscopy_quadrantclassificationmarker',
                'ordering': ['time_ms', 'id'],
                'indexes': [models.Index(fields=['patient', 'time_ms'], name='laparoscopy_patient_e98295_idx'), models.Index(fields=['patient', 'quadrant_type'], name='laparoscopy_patient_0b0895_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'time_ms'), name='laparo_unique_patient_quadrant_marker_time')],
            },
        ),
        migrations.CreateModel(
            name='QuadrantTypeUserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('quadrant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colors', to='laparoscopy.quadranttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_quadrant_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_quadranttypeusercolor',
                'unique_together': {('quadrant_type', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RegionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('brush', 'Brush'), ('eraser', 'Eraser'), ('polygon', 'Polygon')], max_length=20)),
                ('frame_time', models.FloatField(default=0.0)),
                ('points', models.JSONField(default=list)),
                ('prompt_points', models.JSONField(blank=True, default=list)),
                ('stroke_width', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_laparoscopy_annotations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_annotations', to='laparoscopy.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_laparoscopy_annotations', to=settings.AUTH_USER_MODEL)),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='laparoscopy.regiontype')),
            ],
            options={
                'db_table': 'laparoscopy_regionannotation',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['patient', 'frame_time'], name='laparoscopy_patient_f56b1e_idx'), models.Index(fields=['patient', 'region_type'], name='laparoscopy_patient_728243_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionTypeUserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('region_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colors', to='laparoscopy.regiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_region_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_regiontypeusercolor',
                'unique_together': {('region_type', 'user')},
            },
        ),
    ]
