# Generated by Django 5.2.4 on 2026-05-11 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0002_quadranttype_regiontype_quadrantclassificationmarker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query_params', models.JSONField(default=dict, help_text='Stores folder_ids, modality_slugs, and filters')),
                ('query_summary', models.CharField(blank=True, help_text='Human-readable query summary', max_length=500)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated ZIP file', max_length=1000)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size of export file in bytes')),
                ('patient_count', models.IntegerField(default=0, help_text='Number of patients in export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed')),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('authenticated', 'Any logged-in user'), ('public', 'Anyone with link')], default='private', help_text='Controls who can access the share link', max_length=20)),
                ('share_token', models.CharField(blank=True, help_text='Random token used for share link access', max_length=64, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, help_text='When sharing was last enabled', null=True)),
                ('progress_message', models.CharField(blank=True, help_text='Current phase or progress text', max_length=255)),
                ('progress_percent', models.IntegerField(blank=True, help_text='Progress 0-100', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_export',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='laparoscop_user_id_3b9fd5_idx'),
                    models.Index(fields=['status', 'created_at'], name='laparoscop_status_634320_idx'),
                ],
            },
        ),
    ]
