# Generated by Django 5.2.4 on 2026-05-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0003_export'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='export',
            new_name='laparoscopy_user_id_2fb695_idx',
            old_name='laparoscop_user_id_3b9fd5_idx',
        ),
        migrations.RenameIndex(
            model_name='export',
            new_name='laparoscopy_status_1d47e2_idx',
            old_name='laparoscop_status_634320_idx',
        ),
    ]
