# Generated by Django 5.2.4 on 2026-07-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0004_rename_laparoscop_user_id_3b9fd5_idx_laparoscopy_user_id_2fb695_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('project_manager', 'Project Manager')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='laparoscopy.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_folder_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laparoscopy_folder_access',
                'indexes': [models.Index(fields=['folder'], name='laparoscopy_folder__53e45c_idx'), models.Index(fields=['user'], name='laparoscopy_user_id_12c002_idx'), models.Index(fields=['role'], name='laparoscopy_role_5a2514_idx'), models.Index(fields=['folder', 'role'], name='laparoscopy_folder__8e2ab4_idx'), models.Index(fields=['user', 'role'], name='laparoscopy_user_id_26e788_idx')],
                'unique_together': {('user', 'folder')},
            },
        ),
    ]
