# Generated by Django 5.2.4 on 2026-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0007_export_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Expose this folder (and its patients) in the anonymous public demo at /demo/<domain>/. Only anonymized or synthetic studies may be flagged.'),
        ),
    ]
