# Generated by Django 5.2.15 on 2026-08-06 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_alter_project_options_project_domain_and_more'),
        ('laparoscopy', '0008_folder_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_folders', to='common.project'),
        ),
        migrations.AddField(
            model_name='patient',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laparoscopy_patients', to='common.project'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project'], name='laparoscopy_project_ee20d8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project'], name='laparoscopy_project_693f52_idx'),
        ),
    ]
