# Generated by Django 5.2.15 on 2026-08-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_project_disabled_steps'),
        ('laparoscopy', '0010_folders_to_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaparoscopyProject',
            fields=[
            ],
            options={
                'verbose_name': 'Laparoscopy project',
                'verbose_name_plural': 'Laparoscopy projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.project',),
        ),
    ]
