# Generated by Django 5.2.15 on 2026-09-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laparoscopy', '0014_remove_patient_dataset_delete_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_demo',
        ),
    ]
