from django.db import migrations


class Migration(migrations.Migration):
    """Drop the tables that stored laparoscopy video annotations.

    Plain DeleteModels, children before parents. The autogenerated field-by-field form
    fails on MySQL: it removes a foreign key and only then alters the unique_together
    that names it.
    """

    dependencies = [
        ('laparoscopy', '0015_remove_folder_is_demo'),
    ]

    operations = [
        migrations.DeleteModel(name='RegionTypeUserColor'),
        migrations.DeleteModel(name='QuadrantTypeUserColor'),
        migrations.DeleteModel(name='QuadrantClassificationMarker'),
        migrations.DeleteModel(name='RegionAnnotation'),
        migrations.DeleteModel(name='RegionType'),
        migrations.DeleteModel(name='QuadrantType'),
    ]
