"""The report-template content this platform ships with.

Transcribed mechanically from the 367 lines of hardcoded HTML that
``templates/common/sections/report_template_section.html`` used to be, so the clinical
wording is byte-identical to what clinicians have been reading: 16 brain fields, 11
maxillofacial, and three urology sets (10 MRI, 6 confocal, 7 digital pathology), each in
English, Italian and German.

This is **seed data, not the source of truth.** ``manage.py seed_report_templates``
creates the rows once; after that the admin owns them and re-running the command leaves
edits alone. Changing a string here does not change a database that has already been
seeded -- that is the point of the feature, and ``--force`` is the explicit way to
override it.

Laparoscopy is deliberately absent: it never had a checklist, and the panel renders
nothing rather than inventing one.

``key`` is the stable identifier a structured report is filed under, derived from the
English label. It is what the LLM is asked to emit as a section heading, so renaming one
orphans the corresponding section of every report already produced.
"""

TEMPLATES = (
    {
        "domain": "brain",
        "modality_slug": "",
        "name": "Brain report",
        "icon": "",
        "subtitle_en": "", "subtitle_it": "", "subtitle_de": "",
        "fields": (
            {
                "key": "side_of_tumor_center",
                "label_en": "Side of Tumor Center",
                "label_it": "Lato del Centro del Tumore",
                "label_de": "Seite des Tumorzentrums",
                "description_en": "Anatomical laterality of the tumor center from the barycenter position relative to the brain midline (left, right, midline).",
                "description_it": "Lateralità anatomica del centro del tumore in base alla posizione del baricentro rispetto alla linea mediana (sinistra, destra, mediana).",
                "description_de": "Anatomische Lateralität des Tumorzentrums anhand des Schwerpunkts relativ zur Mittellinie (links, rechts, Mittellinie).",
            },
            {
                "key": "enhancement_quality",
                "label_en": "Enhancement Quality",
                "label_it": "Qualità dell'Enhancement",
                "label_de": "Anreicherungsqualität",
                "description_en": "Qualitative assessment of CET contrast enhancement — whether enhancement is present and how pronounced.",
                "description_it": "Valutazione qualitativa dell'enhancement CET — presenza e intensità.",
                "description_de": "Qualitative Beurteilung der CET-Anreicherung — Vorhandensein und Ausprägung.",
            },
            {
                "key": "enhancing_margin_definition",
                "label_en": "Enhancing Margin Definition",
                "label_it": "Definizione del Margine Enhancing",
                "label_de": "Definition des anreichernden Randes",
                "description_en": "Whether most of the outer margin of the enhancement is well or poorly defined.",
                "description_it": "Se il margine esterno dell'enhancement è ben definito o scarsamente definito.",
                "description_de": "Ob der äußere Rand der Anreicherung gut oder schlecht abgegrenzt ist.",
            },
            {
                "key": "non_enhancing_margin_definition",
                "label_en": "Non-Enhancing Margin Definition",
                "label_it": "Definizione del Margine Non-Enhancing",
                "label_de": "Definition des nicht-anreichernden Randes",
                "description_en": "Whether most of the outer margin of the non-enhancing component is well or poorly defined.",
                "description_it": "Se il margine esterno della componente non-enhancing è ben definito o scarsamente definito.",
                "description_de": "Ob der äußere Rand der nicht-anreichernden Komponente gut oder schlecht abgegrenzt ist.",
            },
            {
                "key": "intratumoral_hemorrhage",
                "label_en": "Intratumoral Hemorrhage",
                "label_it": "Emorragia Intratumorale",
                "label_de": "Intratumorale Einblutung",
                "description_en": "Whether intrinsic hemorrhage is visible anywhere in the tumor matrix.",
                "description_it": "Se un'emorragia intrinseca è visibile nella matrice tumorale.",
                "description_de": "Ob eine intrinsische Einblutung in der Tumormatrix sichtbar ist.",
            },
            {
                "key": "tumor_heterogeneity",
                "label_en": "Tumor Heterogeneity",
                "label_it": "Eterogeneità del Tumore",
                "label_de": "Tumorheterogenität",
                "description_en": "Degree of heterogeneity of the internal architecture of the tumor.",
                "description_it": "Grado di eterogeneità dell'architettura interna del tumore.",
                "description_de": "Grad der Heterogenität der inneren Architektur des Tumors.",
            },
            {
                "key": "number_of_lesions",
                "label_en": "Number of Lesions",
                "label_it": "Numero di Lesioni",
                "label_de": "Anzahl der Läsionen",
                "description_en": "Number of independent lesions observed in the brain.",
                "description_it": "Numero di lesioni indipendenti osservate nel cervello.",
                "description_de": "Anzahl der unabhängigen Läsionen im Gehirn.",
            },
            {
                "key": "lesion_type",
                "label_en": "Lesion Type",
                "label_it": "Tipo di Lesione",
                "label_de": "Läsionstyp",
                "description_en": "Single, multicentric, or multifocal.",
                "description_it": "Singola, multicentrica o multifocale.",
                "description_de": "Solitär, multizentrisch oder multifokal.",
            },
            {
                "key": "ependymal_invasion",
                "label_en": "Ependymal Invasion",
                "label_it": "Invasione Ependimale",
                "label_de": "Ependymale Invasion",
                "description_en": "Whether the TC abuts any adjacent ependymal surface.",
                "description_it": "Se il TC è a contatto con una superficie ependimale adiacente.",
                "description_de": "Ob das TC an eine angrenzende Ependymoberfläche angrenzt.",
            },
            {
                "key": "depth_of_tc",
                "label_en": "Depth of TC",
                "label_it": "Profondità del TC",
                "label_de": "Tiefe des TC",
                "description_en": "Cortical, subcortical white matter, deep white matter, or basal nuclei.",
                "description_it": "Corticale, sostanza bianca sottocorticale, sostanza bianca profonda o nuclei della base.",
                "description_de": "Kortikal, subkortikale/tiefe weiße Substanz oder Basalganglien.",
            },
            {
                "key": "macroarea_of_tumor_center",
                "label_en": "Macroarea of Tumor Center",
                "label_it": "Macroarea del Centro del Tumore",
                "label_de": "Makrobereich des Tumorzentrums",
                "description_en": "Lobe in which the barycenter lies, obtained from the atlas.",
                "description_it": "Lobo in cui ricade il baricentro, ottenuto dall'atlante.",
                "description_de": "Lobus, in dem der Schwerpunkt liegt, aus dem Atlas ermittelt.",
            },
            {
                "key": "midline_shift_mm",
                "label_en": "Midline Shift (mm)",
                "label_it": "Spostamento della Linea Mediana (mm)",
                "label_de": "Mittellinienverlagerung (mm)",
                "description_en": "Shift of the midline caused by the tumor mass, in millimeters.",
                "description_it": "Spostamento della linea mediana causato dalla massa, in millimetri.",
                "description_de": "Durch die Tumormasse verursachte Verlagerung der Mittellinie in mm.",
            },
            {
                "key": "tumor_shape",
                "label_en": "Tumor Shape",
                "label_it": "Forma del Tumore",
                "label_de": "Tumorform",
                "description_en": "Approximate shape of the tumor mass.",
                "description_it": "Forma approssimativa della massa tumorale.",
                "description_de": "Ungefähre Form der Tumormasse.",
            },
            {
                "key": "tumor_origin",
                "label_en": "Tumor Origin",
                "label_it": "Origine del Tumore",
                "label_de": "Tumorursprung",
                "description_en": "Periventricular, gyral, or deep white matter.",
                "description_it": "Periventricolare, girale o sostanza bianca profonda.",
                "description_de": "Periventrikulär, gyral oder tiefe weiße Substanz.",
            },
            {
                "key": "tumor_crosses_the_midline",
                "label_en": "Tumor Crosses the Midline",
                "label_it": "Il Tumore Attraversa la Linea Mediana",
                "label_de": "Tumor überschreitet die Mittellinie",
                "description_en": "Whether the tumor crosses the midline.",
                "description_it": "Se il tumore attraversa la linea mediana.",
                "description_de": "Ob der Tumor die Mittellinie überschreitet.",
            },
            {
                "key": "subject_specific_findings",
                "label_en": "Subject-Specific Findings",
                "label_it": "Reperti Specifici del Soggetto",
                "label_de": "Subjektspezifische Befunde",
                "description_en": "Any findings not covered by a predefined category.",
                "description_it": "Reperti non coperti da alcuna categoria predefinita.",
                "description_de": "Befunde, die keiner vordefinierten Kategorie zugeordnet sind.",
            },
        ),
    },
    {
        "domain": "maxillo",
        "modality_slug": "",
        "name": "Maxillo report",
        "icon": "",
        "subtitle_en": "", "subtitle_it": "", "subtitle_de": "",
        "fields": (
            {
                "key": "skeletal_class_sagittal",
                "label_en": "Skeletal Class (Sagittal)",
                "label_it": "Classe Scheletrica (Sagittale)",
                "label_de": "Skelettklasse (Sagittal)",
                "description_en": "Antero-posterior jaw relationship — Class I, II, or III.",
                "description_it": "Rapporto antero-posteriore tra le arcate — Classe I, II o III.",
                "description_de": "Antero-posteriore Kieferrelation — Klasse I, II oder III.",
            },
            {
                "key": "vertical_pattern",
                "label_en": "Vertical Pattern",
                "label_it": "Pattern Verticale",
                "label_de": "Vertikales Muster",
                "description_en": "Facial growth pattern — hypodivergent, normodivergent, or hyperdivergent.",
                "description_it": "Pattern di crescita facciale — ipodivergente, normodivergente o iperdivergente.",
                "description_de": "Faziales Wachstumsmuster — hypodivergent, normodivergent oder hyperdivergent.",
            },
            {
                "key": "transverse_relationship",
                "label_en": "Transverse Relationship",
                "label_it": "Rapporto Trasverso",
                "label_de": "Transversale Relation",
                "description_en": "Presence of crossbite or transverse discrepancy between arches.",
                "description_it": "Presenza di crossbite o discrepanza trasversale tra le arcate.",
                "description_de": "Vorliegen eines Kreuzbisses oder transversaler Diskrepanz zwischen den Zahnbögen.",
            },
            {
                "key": "dental_midlines",
                "label_en": "Dental Midlines",
                "label_it": "Linee Mediane Dentali",
                "label_de": "Dentale Mittellinien",
                "description_en": "Coincidence of upper/lower dental midlines with the facial midline.",
                "description_it": "Coincidenza delle linee mediane superiore/inferiore con la mediana facciale.",
                "description_de": "Übereinstimmung der oberen/unteren Mittellinie mit der Gesichtsmittellinie.",
            },
            {
                "key": "overjet",
                "label_en": "Overjet",
                "label_it": "Overjet",
                "label_de": "Overjet",
                "description_en": "Horizontal overlap of the incisors, in millimeters.",
                "description_it": "Sovrapposizione orizzontale degli incisivi, in millimetri.",
                "description_de": "Horizontale Frontzahnstufe in Millimetern.",
            },
            {
                "key": "overbite",
                "label_en": "Overbite",
                "label_it": "Overbite",
                "label_de": "Overbite",
                "description_en": "Vertical overlap of the incisors, in millimeters or as a percentage.",
                "description_it": "Sovrapposizione verticale degli incisivi, in millimetri o percentuale.",
                "description_de": "Vertikale Frontzahnstufe in Millimetern oder Prozent.",
            },
            {
                "key": "molar_canine_relationship",
                "label_en": "Molar & Canine Relationship",
                "label_it": "Rapporto Molare e Canino",
                "label_de": "Molaren- & Eckzahnrelation",
                "description_en": "Angle classification of molar and canine occlusion, by side.",
                "description_it": "Classificazione di Angle dell'occlusione molare e canina, per lato.",
                "description_de": "Angle-Klassifikation der Molaren- und Eckzahnokklusion, seitenweise.",
            },
            {
                "key": "crowding_spacing",
                "label_en": "Crowding / Spacing",
                "label_it": "Affollamento / Spaziatura",
                "label_de": "Engstand / Lücken",
                "description_en": "Space discrepancy in the upper and lower arches.",
                "description_it": "Discrepanza di spazio nelle arcate superiore e inferiore.",
                "description_de": "Platzdiskrepanz im Ober- und Unterkiefer.",
            },
            {
                "key": "tmj_findings",
                "label_en": "TMJ Findings",
                "label_it": "Reperti ATM",
                "label_de": "Kiefergelenk-Befunde",
                "description_en": "Condylar morphology, symmetry and any degenerative signs.",
                "description_it": "Morfologia condilare, simmetria ed eventuali segni degenerativi.",
                "description_de": "Kondylenmorphologie, Symmetrie und degenerative Zeichen.",
            },
            {
                "key": "airway_soft_tissue",
                "label_en": "Airway / Soft Tissue",
                "label_it": "Vie Aeree / Tessuti Molli",
                "label_de": "Atemweg / Weichgewebe",
                "description_en": "Airway patency and relevant soft-tissue profile notes.",
                "description_it": "Pervietà delle vie aeree e note sul profilo dei tessuti molli.",
                "description_de": "Atemwegsdurchgängigkeit und relevante Weichteilprofil-Notizen.",
            },
            {
                "key": "subject_specific_findings",
                "label_en": "Subject-Specific Findings",
                "label_it": "Reperti Specifici del Soggetto",
                "label_de": "Subjektspezifische Befunde",
                "description_en": "Any findings not covered by a predefined category.",
                "description_it": "Reperti non coperti da alcuna categoria predefinita.",
                "description_de": "Befunde, die keiner vordefinierten Kategorie zugeordnet sind.",
            },
        ),
    },
    {
        "domain": "urology",
        "modality_slug": "mri",
        "name": "Urology — Multiparametric Magnetic Resonance",
        "icon": "fas fa-magnet me-1",
        "subtitle_en": "Multiparametric Magnetic Resonance",
        "subtitle_it": "Risonanza Magnetica Multiparametrica",
        "subtitle_de": "Multiparametrische Magnetresonanztomographie",
        "fields": (
            {
                "key": "prostate_volume_and_psa_density",
                "label_en": "Prostate Volume and PSA Density",
                "label_it": "Volume Prostatico e Densità del PSA",
                "label_de": "Prostatavolumen und PSA-Dichte",
                "description_en": "Volumetric measurement of the prostate gland (in cc or ml) and PSA density calculation.",
                "description_it": "Misurazione volumetrica della ghiandola (in cc o ml) e calcolo correlato della densità del PSA (PSA density).",
                "description_de": "Volumetrische Messung der Prostata (in cm³ oder ml) und Berechnung der PSA-Dichte.",
            },
            {
                "key": "index_lesion_location_and_sector",
                "label_en": "Index Lesion Location and Sector",
                "label_it": "Sede e Settore della Lesione Indice",
                "label_de": "Lage und Sektor der Indexläsion",
                "description_en": "Anatomical site according to the 39-sector map (peripheral zone, transition zone, anterior fibromuscular stroma; apex, mid-gland, base; left or right).",
                "description_it": "Localizzazione anatomica secondo la mappa a 39 settori (zona periferica, zona di transizione, stroma fibromuscolare anteriore; apice, medio-ghiandola, base; lato destro o sinistro).",
                "description_de": "Anatomische Lokalisation gemäß 39-Sektoren-Karte (periphere Zone, Transitionszone, anteriores fibromuskuläres Stroma; Apex, Mitteldrüse, Basis; links oder rechts).",
            },
            {
                "key": "lesion_dimensions",
                "label_en": "Lesion Dimensions",
                "label_it": "Dimensioni della Lesione",
                "label_de": "Läsionsabmessungen",
                "description_en": "Maximal diameter of the primary target lesion, specifying axial and longitudinal dimensions in millimeters.",
                "description_it": "Diametro massimo della lesione target principale, espresso in millimetri (dimensione assiale e longitudinale).",
                "description_de": "Maximaler Durchmesser der Hauptläsion mit Angabe der axialen und longitudinalen Maße in Millimetern.",
            },
            {
                "key": "pi_rads_score",
                "label_en": "PI-RADS Score",
                "label_it": "Punteggio PI-RADS",
                "label_de": "PI-RADS-Score",
                "description_en": "Overall risk category (1 to 5) assigned to the index lesion and secondary foci according to PI-RADS v2.1 criteria.",
                "description_it": "Categoria di rischio globale (da 1 a 5) assegnata alla lesione indice ed eventuali focolai secondari secondo i criteri PI-RADS v2.1.",
                "description_de": "Gesamtrisikokategorie (1 bis 5) für die Indexläsion und sekundäre Herde gemäß PI-RADS v2.1.",
            },
            {
                "key": "t2_signal_and_diffusion_restriction_adc",
                "label_en": "T2 Signal and Diffusion Restriction (ADC)",
                "label_it": "Intensità T2 e Restrizione in Diffusione (ADC)",
                "label_de": "T2-Signal und Diffusionsrestriktion (ADC)",
                "description_en": "Degree of hypointensity on T2 sequences and severity of restricted diffusion on the ADC map and high b-value images.",
                "description_it": "Morfologia e grado di ipointensità nelle sequenze T2 (focale, lenticolare o cuneiforme) e intensità della restrizione nella mappa ADC ad alto b-value.",
                "description_de": "Grad der Hypointensität auf T2-Sequenzen und Ausmaß der Diffusionsrestriktion auf der ADC-Karte.",
            },
            {
                "key": "dynamic_contrast_enhancement",
                "label_en": "Dynamic Contrast Enhancement",
                "label_it": "Impregnazione di Contrasto Dinamica",
                "label_de": "Dynamische Kontrastmittelanreicherung",
                "description_en": "Assessment of contrast enhancement: presence or absence of early and focal wash-in/wash-out compared to normal parenchyma.",
                "description_it": "Valutazione della perfusione con gadolinio: presenza o assenza di enhancement precoce e focale (wash-in/wash-out) rispetto al parenchima di fondo.",
                "description_de": "Beurteilung der Kontrastmittelperfusion: Vorhandensein oder Fehlen einer frühzeitigen fokalen Anreicherung.",
            },
            {
                "key": "extraprostatic_extension",
                "label_en": "Extraprostatic Extension",
                "label_it": "Estensione Extracapsulare",
                "label_de": "Extraprostatische Ausbreitung",
                "description_en": "Evidence of capsule transgression: length of capsular contact, bulging, asymmetry, or frank cortical breach.",
                "description_it": "Segni di invasione della capsula prostatica: ampiezza del contatto capsulare, bulging, asimmetria o franche interruzioni della corticale.",
                "description_de": "Kapselüberschreitung: Kapselkontaktlänge, Bulging, Asymmetrie oder Kapseldurchbruch.",
            },
            {
                "key": "seminal_vesicle_invasion",
                "label_en": "Seminal Vesicle Invasion",
                "label_it": "Invasione delle Vescicole Seminali",
                "label_de": "Samenblaseninvagination",
                "description_en": "Unilateral or bilateral involvement of the base or tubular architecture of the seminal vesicles.",
                "description_it": "Coinvolgimento mono o bilaterale della base o della struttura tubulare delle vescicole seminali.",
                "description_de": "Ein- oder beidseitige Infiltration der Basis oder tubulären Architektur der Samenblasen.",
            },
            {
                "key": "neurovascular_bundle_and_bladder_neck",
                "label_en": "Neurovascular Bundle and Bladder Neck",
                "label_it": "Rapporti con Fasci Neurovascolari e Collo Vescicale",
                "label_de": "Gefäß-Nerven-Bündel und Blasenhals",
                "description_en": "Assessment of contact with or abutment of left/right neurovascular bundles, bladder neck, and external urethral sphincter.",
                "description_it": "Valutazione del contatto o inglobamento dei fasci neurovascolari destro e sinistro, del collo vescicale e dello sfintere uretrale striato.",
                "description_de": "Verhältnis zum rechten/linken neurovaskulären Bündel, Blasenhals und äußeren Harnröhrensphinkter.",
            },
            {
                "key": "regional_lymph_nodes_and_pelvic_skeleton",
                "label_en": "Regional Lymph Nodes and Pelvic Skeleton",
                "label_it": "Linfonodi Regionali e Scheletro del Bacino",
                "label_de": "Regionale Lymphknoten und Beckenskelett",
                "description_en": "Presence of suspicious lymphadenopathy in obturator and iliac chains, and any pelvic bone alterations.",
                "description_it": "Presenza di linfoadenopatie sospette nelle stazioni otturatorie e iliache, ed eventuali alterazioni ossee del bacino.",
                "description_de": "Verdächtige Lymphknoten in Obturator- und Iliakalstationen sowie eventuelle ossäre Läsionen.",
            },
        ),
    },
    {
        "domain": "urology",
        "modality_slug": "confocal",
        "name": "Urology — Fluorescence Confocal Microscopy",
        "icon": "fas fa-eye me-1",
        "subtitle_en": "Fluorescence Confocal Microscopy",
        "subtitle_it": "Microscopia Confocale Real-Time",
        "subtitle_de": "Fluoreszenz-Konfokalmikroskopie",
        "fields": (
            {
                "key": "specimen_adequacy_and_core_cellularity",
                "label_en": "Specimen Adequacy and Core Cellularity",
                "label_it": "Adeguatezza del Prelievo e Rappresentatività",
                "label_de": "Probenadäquanz und Zellularität",
                "description_en": "Assessment of tissue adequacy, cellularity, and target representation prior to downstream processing.",
                "description_it": "Valutazione dell'adeguatezza del campione, cellularità e reale rappresentatività del tessuto bersaglio prima del processamento definitivo.",
                "description_de": "Beurteilung der Gewebeadäquanz, Zellularität und Repräsentativität des Zielgewebes vor der definitiven Aufarbeitung.",
            },
            {
                "key": "glandular_architecture_and_acinar_packing",
                "label_en": "Glandular Architecture and Acinar Packing",
                "label_it": "Architettura Ghiandolare ed Orientamento Acinare",
                "label_de": "Drüsenarchitektur und Azinusformation",
                "description_en": "Optical evaluation of gland crowding, fused or cribriform acinar structures, and lumen preservation in fresh tissue.",
                "description_it": "Valutazione ottica dell'affollamento ghiandolare, presenza di acini fusi o cribriformi e preservazione del lume su tessuto fresco.",
                "description_de": "Optische Beurteilung von Drüsendichte, fusionierten oder kribriformen Azinusstrukturen und Lumenerhalt am Frischgewebe.",
            },
            {
                "key": "nuclear_atypia_and_cellular_pleomorphism",
                "label_en": "Nuclear Atypia and Cellular Pleomorphism",
                "label_it": "Morfologia Nucleare ed Atipia Cellulare",
                "label_de": "Zellkernatypien und Pleomorphie",
                "description_en": "Fluorescence confocal detection of nuclear enlargement, hyperchromasia, prominent nucleoli, and loss of polarity.",
                "description_it": "Riconoscimento confocale a fluorescenza di ingrandimento nucleare, ipercromasia, nucleoli prominenti e perdita della polarità.",
                "description_de": "Fluoreszenz-konfokaler Nachweis von Kernvergrößerung, Hyperchromasie, prominenten Nukleolen und Polaritätsverlust.",
            },
            {
                "key": "basal_cell_layer_integrity",
                "label_en": "Basal Cell Layer Integrity",
                "label_it": "Integrità dello Strato di Cellule Basali",
                "label_de": "Integrität der Basalzellschicht",
                "description_en": "Assessment of basal cell layer preservation versus complete disruption, a key hallmark distinguishing benign glands from carcinoma.",
                "description_it": "Verifica della presenza continua o dell'interruzione/perdita dello strato di cellule basali, criterio cardine di malignità.",
                "description_de": "Überprüfung auf Erhalt oder Unterbrechung/Verlust der Basalzellschicht als zentrales Malignitätskriterium.",
            },
            {
                "key": "stromal_infiltration_and_desmoplasia",
                "label_en": "Stromal Infiltration and Desmoplasia",
                "label_it": "Infiltrazione Stromale e Reazione Desmoplastica",
                "label_de": "Stromainfiltration und desmoplastische Reaktion",
                "description_en": "Identification of infiltrating neoplastic cords or isolated malignant cells disrupting the fibromuscular stroma.",
                "description_it": "Identificazione di cordoni neoplastici infiltranti o singole cellule tumorali nello stroma fibromuscolare prostatico.",
                "description_de": "Nachweis infiltrierender Tumorzellstränge oder Einzelzellen im fibromuskulären Prostatastroma.",
            },
            {
                "key": "real_time_surgical_margin_status_neurosafe",
                "label_en": "Real-Time Surgical Margin Status (NeuroSAFE)",
                "label_it": "Margini Chirurgici in Tempo Reale (NeuroSAFE)",
                "label_de": "Intraoperative Schnittrandbeurteilung (NeuroSAFE)",
                "description_en": "Intraoperative fresh-tissue margin evaluation for neurovascular bundle-sparing prostatectomy (margin positive vs negative).",
                "description_it": "Valutazione intraoperatoria su tessuto fresco dei margini di resezione per il risparmio dei fasci neurovascolari (margine negativo o positivo).",
                "description_de": "Intraoperative Schnellschnitt-orientierte Beurteilung der Resektionsränder zum Erhalt des Gefäß-Nerven-Bündels (negativ vs. positiv).",
            },
        ),
    },
    {
        "domain": "urology",
        "modality_slug": "wsi",
        "name": "Urology — Digital Histopathology",
        "icon": "fas fa-microscope me-1",
        "subtitle_en": "Digital Histopathology",
        "subtitle_it": "Istopatologia Digitale",
        "subtitle_de": "Digitale Histopathologie",
        "fields": (
            {
                "key": "tumor_histotype",
                "label_en": "Tumor Histotype",
                "label_it": "Istotipo Tumorale",
                "label_de": "Tumorhistotyp",
                "description_en": "Histological classification of the neoplasm (usual acinar adenocarcinoma, ductal, mucinous, signet-ring, or neuroendocrine variant).",
                "description_it": "Classificazione istologica della neoplasia (adenocarcinoma acinare usuale, variante duttale, mucinosa, a cellule ad anello con castone o neuroendocrina).",
                "description_de": "Histologische Tumorklassifikation (azinäres Adenokarzinom, duktale Variante, muzinös oder neuroendokrin).",
            },
            {
                "key": "gleason_score_and_isup_grade_group",
                "label_en": "Gleason Score and ISUP Grade Group",
                "label_it": "Gleason Score e Grade Group ISUP",
                "label_de": "Gleason-Score und ISUP-Gradgruppe",
                "description_en": "Primary and secondary architectural pattern (e.g. 3+4=7 or 4+3=7) and assigned ISUP Grade Group (1 to 5).",
                "description_it": "Definizione del pattern primario e secondario (es. 3+4=7 o 4+3=7) e assegnazione del rispettivo Grade Group ISUP da 1 a 5.",
                "description_de": "Primäres und sekundäres Wachstumsmuster (z.B. 3+4=7) und ISUP-Gradgruppe (1 bis 5).",
            },
            {
                "key": "pattern_4_or_5_percentage_and_cribriform_architecture",
                "label_en": "Pattern 4 or 5 Percentage and Cribriform Architecture",
                "label_it": "Percentuale Pattern 4 o 5 e Architettura Cribriforme",
                "label_de": "Anteil Pattern 4 oder 5 und kribriforme Architektur",
                "description_en": "Quantification of poorly differentiated tumor components and presence of cribriform pattern (adverse prognostic factor).",
                "description_it": "Quantificazione percentuale delle componenti tumorali scarsamente differenziate e riscontro di pattern cribriforme, importante indicatore prognostico.",
                "description_de": "Prozentualer Anteil schlecht differenzierter Muster und Nachweis kribriformer Formationen.",
            },
            {
                "key": "intraductal_carcinoma",
                "label_en": "Intraductal Carcinoma",
                "label_it": "Carcinoma Intraduttale",
                "label_de": "Intraduktales Karzinom",
                "description_en": "Presence or absence of malignant proliferation within pre-existing ducts or acini with preserved basal cells.",
                "description_it": "Presenza o assenza di proliferazione maligna all'interno di dotti o acini preesistenti con parziale conservazione dello strato basale.",
                "description_de": "Vorhandensein oder Fehlen maligner Proliferation in präexistenten Gängen mit erhaltenen Basalzellen.",
            },
            {
                "key": "perineural_and_vascular_invasion",
                "label_en": "Perineural and Vascular Invasion",
                "label_it": "Invasione Perineurale e Vascolare",
                "label_de": "Perineurale und Vaskuläre Invasion",
                "description_en": "Identification of tumor cells along perineural nerve sheaths and lymphovascular space invasion.",
                "description_it": "Rilevamento di cellule neoplastiche lungo i tronchi nervosi perineurali e angioinvasione nei vasi ematici o linfatici.",
                "description_de": "Infiltration perineuraler Spalträume und Nachweis von Angioinvasion in Blut- oder Lymphgefäßen.",
            },
            {
                "key": "tumor_extent_in_specimen_and_surgical_margins",
                "label_en": "Tumor Extent in Specimen and Surgical Margins",
                "label_it": "Estensione Tumorale nel Prelievo e Margini Chirurgici",
                "label_de": "Tumorausdehnung im Präparat und Resektionsränder",
                "description_en": "Linear millimeters and percentage of tumor tissue per biopsy core; if radical prostatectomy, surgical margin status (R0 negative or R1 positive with extent).",
                "description_it": "Millimetri lineari e percentuale di tessuto tumorale per carota bioptica; in caso di pezzo operatorio, stato dei margini chirurgici (R0 negativo o R1 positivo con sede ed estensione).",
                "description_de": "Tumorbefall in Millimetern und Prozent pro Stanzbiopsie; bei Prostatektomie Resektionsrandstatus (R0 oder R1).",
            },
            {
                "key": "non_tumor_parenchyma_and_concomitant_lesions",
                "label_en": "Non-Tumor Parenchyma and Concomitant Lesions",
                "label_it": "Parenchima Non Tumorale e Lesioni Concomitanti",
                "label_de": "Nicht-tumoröses Parenchym und Begleitbefunde",
                "description_en": "Benign or pre-neoplastic findings in surrounding tissue (benign prostatic hyperplasia, prostatitis, atrophy, atypical small acinar proliferation, or high-grade PIN).",
                "description_it": "Reperti benigni o preneoplastici nel tessuto circostante (iperplasia prostatica benigna, prostatite, atrofia, atipia a piccoli acini o PIN di alto grado).",
                "description_de": "Gutartige oder prämaligne Veränderungen (benigne Prostatahyperplasie, Prostatitis, Atrophie, ASAP oder High-Grade-PIN).",
            },
        ),
    },
)
