# Generated by Django 5.2.15 on 2026-08-26 15:13

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0021_patient_project_required'),
        ('common', '0045_cleanup_annotation_methods'),
        ('laparoscopy', '0013_patient_project_required'),
        ('maxillo', '0029_patient_project_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='The integer written into labelmaps. Immutable once published.')),
                ('code', models.CharField(blank=True, default=None, help_text='External identifier (e.g. an FDI tooth code). NULL if none.', max_length=60, null=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='#rrggbb suggestion for viewers; not authoritative.', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Retired labels stay readable; deleting one would orphan voxels.')),
            ],
            options={
                'db_table': 'annotations_label_definition',
                'ordering': ['schema_id', 'order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ios_landmarks', 'IOS landmarks'), ('intraoral_segmentation', 'Intraoral tooth segmentation'), ('occlusion_classification', 'Occlusion classification'), ('panoramic_arch', 'Panoramic arch'), ('video_regions', 'Video region annotation'), ('video_quadrants', 'Video quadrant markers'), ('voice_caption', 'Voice caption'), ('volume_segmentation', 'Volume segmentation'), ('measurements', 'Measurements')], max_length=40)),
                ('domain', models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy')], default='maxillo', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('ever_annotated', models.BooleanField(default=False, help_text='Monotonic: set true the first time human annotation work is recorded and never cleared. Decision #18 -- deleting the work does not unfreeze the raw data it was drawn on, because the bytes were already interpreted and the record has to stay explicable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotation_method', models.ForeignKey(blank=True, help_text='The project-level gate for this work, where one exists. NULL means the registry does not gate this kind (the panoramic arch, whose editability is governed by the annotation lock instead).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_sets', to='common.annotationmethod')),
                ('brain_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sets', to='brain.patient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotation_sets', to=settings.AUTH_USER_MODEL)),
                ('laparoscopy_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sets', to='laparoscopy.patient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sets', to='maxillo.patient')),
            ],
            options={
                'db_table': 'annotations_annotation_set',
                'ordering': ['-updated_at', 'id'],
            },
            bases=(common.models.DomainFKAccessorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnnotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(help_text='1-based and gapless. Allocated by the write, not read beforehand.')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('prediction', 'Prediction'), ('corrected_prediction', 'Corrected prediction'), ('migration', 'Migration'), ('import', 'Import')], default='manual', max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source_fingerprint', models.JSONField(blank=True, default=dict, help_text='{identity_key: content_hash} for every target, as of this revision.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_revisions', to=settings.AUTH_USER_MODEL)),
                ('annotation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='annotations.annotationset')),
            ],
            options={
                'db_table': 'annotations_annotation_revision',
                'ordering': ['annotation_set_id', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="What this target is to the set: 'volume', 'segmentation', 'image', 'video'.", max_length=40)),
                ('primary_slot', models.PositiveSmallIntegerField(blank=True, default=None, help_text='1 on the primary target, NULL on every other. A nullable slot, not a conditional constraint, because MySQL drops those silently (F12).', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='annotations.annotationset')),
            ],
            options={
                'db_table': 'annotations_annotation_target',
                'ordering': ['annotation_set_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('whole_resource', 'Whole resource'), ('frame', 'Frame'), ('slice', 'Slice'), ('temporal_interval', 'Temporal interval'), ('spatial_bounds', 'Spatial bounds'), ('segment', 'Segment')], max_length=32)),
                ('coordinate_system', models.CharField(choices=[('patient_lps_mm', 'Patient LPS (mm)'), ('patient_ras_mm', 'Patient RAS (mm)'), ('volume_voxel', 'Volume voxel (IJK)'), ('image_pixel', 'Image pixel'), ('image_normalized', 'Image normalized'), ('slice_pixel', 'Slice pixel'), ('video_pixel', 'Video pixel'), ('video_normalized', 'Video normalized'), ('resource_local', 'Resource local'), ('none', 'None')], help_text="Never blank. 'none' where the selection has no geometry.", max_length=32)),
                ('frame_index', models.PositiveIntegerField(blank=True, null=True)),
                ('slice_axis', models.CharField(blank=True, choices=[('axial', 'Axial'), ('coronal', 'Coronal'), ('sagittal', 'Sagittal'), ('oblique', 'Oblique')], max_length=16)),
                ('slice_index', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('end_time_ms', models.PositiveIntegerField(blank=True, help_text='Exclusive end of a half-open interval. Equal to start for an instant.', null=True)),
                ('segment_value', models.PositiveIntegerField(blank=True, help_text='Labelmap segment this selector picks out; matches LabelDefinition.value.', null=True)),
                ('bounds', models.JSONField(blank=True, default=dict, help_text="Axis-aligned extent in this selector's coordinate system, when kind=spatial_bounds.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='annotations.annotationtarget')),
            ],
            options={
                'db_table': 'annotations_annotation_selector',
                'ordering': ['target_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Geometry2DItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the revision; not semantic.')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Tool-specific extras. Never a place for coordinates or labels.')),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('polyline', 'Polyline'), ('polygon', 'Polygon'), ('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('circle', 'Circle'), ('freehand', 'Freehand')], max_length=20)),
                ('coordinate_system', models.CharField(choices=[('patient_lps_mm', 'Patient LPS (mm)'), ('patient_ras_mm', 'Patient RAS (mm)'), ('volume_voxel', 'Volume voxel (IJK)'), ('image_pixel', 'Image pixel'), ('image_normalized', 'Image normalized'), ('slice_pixel', 'Slice pixel'), ('video_pixel', 'Video pixel'), ('video_normalized', 'Video normalized'), ('resource_local', 'Resource local'), ('none', 'None')], help_text='Must be one of CoordinateSystem.TWO_D; validated on write.', max_length=32)),
                ('points', models.JSONField(default=list, help_text='[[x, y], ...]. Point counts are validated per geometry_type.')),
                ('closed', models.BooleanField(default=False, help_text='Whether the last point joins the first. Always true for a polygon.')),
                ('stroke_width', models.FloatField(blank=True, help_text="Brush width in the row's own coordinate system, for stroke tools. Part of the geometry, not styling: it is what the mask was painted with.", null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='annotations.annotationrevision')),
                ('selector', models.ForeignKey(blank=True, help_text='Narrows the target (a frame, a slice). NULL applies to the whole target.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationselector')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationtarget')),
                ('label', models.ForeignKey(blank=True, help_text='PROTECT: retiring a label must not silently unlabel existing work.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.labeldefinition')),
            ],
            options={
                'db_table': 'annotations_geometry_2d_item',
                'ordering': ['revision_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventAnnotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the revision; not semantic.')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Tool-specific extras. Never a place for coordinates or labels.')),
                ('event_type', models.CharField(help_text="What is being asserted about, e.g. 'occlusion.sagittal_left'.", max_length=60)),
                ('value', models.CharField(blank=True, help_text='Free-text assertion, for statements no schema covers yet.', max_length=255)),
                ('time_ms', models.PositiveIntegerField(blank=True, help_text='When it applies, for time-stamped events; NULL for a whole-study statement.', null=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='annotations.annotationrevision')),
                ('selector', models.ForeignKey(blank=True, help_text='Narrows the target (a frame, a slice). NULL applies to the whole target.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationselector')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationtarget')),
                ('label', models.ForeignKey(blank=True, help_text='PROTECT: retiring a label must not silently unlabel existing work.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.labeldefinition')),
            ],
            options={
                'db_table': 'annotations_event_item',
                'ordering': ['revision_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabelSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1, help_text="Bump instead of editing: a published version's values are frozen.")),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, default='', help_text='Blank for a schema usable in every domain.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_label_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annotations_label_schema',
                'ordering': ['domain', 'slug', 'version'],
            },
        ),
        migrations.AddField(
            model_name='labeldefinition',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='annotations.labelschema'),
        ),
        migrations.AddField(
            model_name='annotationset',
            name='label_schema',
            field=models.ForeignKey(blank=True, help_text='Required for anything with labels; NULL for pure geometry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_sets', to='annotations.labelschema'),
        ),
        migrations.CreateModel(
            name='SourceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'File'), ('dicom_series', 'DICOM series'), ('dicom_instance', 'DICOM instance'), ('derived_resource', 'Derived resource'), ('logical_volume', 'Logical volume')], max_length=32)),
                ('identity_key', models.CharField(help_text='Canonical identity string. Built by annotations.identity, never by hand.', max_length=255, unique=True)),
                ('file_key', models.CharField(blank=True, help_text="Member key inside a multi-file bundle (FileRegistry.metadata['files']), e.g. 'volume_nifti'. Blank means the row's own file_path.", max_length=60)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=64)),
                ('series_instance_uid', models.CharField(blank=True, max_length=64)),
                ('frame_of_reference_uid', models.CharField(blank=True, help_text='Coordinates in patient_lps_mm are only comparable within one of these.', max_length=64)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of the bytes as of registration. A later mismatch means the resource was rewritten underneath its annotations -- which is what the raw-data lock exists to prevent, and what crosscheck reports.', max_length=64)),
                ('descriptor', models.JSONField(blank=True, default=dict, help_text='Shape, spacing, frame count and other facts needed to interpret coordinates. Descriptive only: never a substitute for reading the file.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, help_text='Set for kind=file and for bundle members; NULL for DICOM and derived kinds.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_resources', to='common.fileregistry')),
            ],
            options={
                'db_table': 'annotations_source_resource',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='annotationtarget',
            name='source_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='annotations.sourceresource'),
        ),
        migrations.CreateModel(
            name='SpatialAnnotation3DItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the revision; not semantic.')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Tool-specific extras. Never a place for coordinates or labels.')),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('polyline', 'Polyline'), ('plane', 'Plane'), ('box', 'Box'), ('sphere', 'Sphere')], max_length=20)),
                ('coordinate_system', models.CharField(choices=[('patient_lps_mm', 'Patient LPS (mm)'), ('patient_ras_mm', 'Patient RAS (mm)'), ('volume_voxel', 'Volume voxel (IJK)'), ('image_pixel', 'Image pixel'), ('image_normalized', 'Image normalized'), ('slice_pixel', 'Slice pixel'), ('video_pixel', 'Video pixel'), ('video_normalized', 'Video normalized'), ('resource_local', 'Resource local'), ('none', 'None')], help_text='Must be one of CoordinateSystem.THREE_D; validated on write.', max_length=32)),
                ('points', models.JSONField(default=list, help_text='[[x, y, z], ...]. Point counts are validated per geometry_type.')),
                ('frame_of_reference_uid', models.CharField(blank=True, help_text='Required for cross-resource comparability of patient-space coordinates. Blank is correct for resource_local, which is scoped to one mesh and has no patient frame at all.', max_length=64)),
                ('label', models.ForeignKey(blank=True, help_text='PROTECT: retiring a label must not silently unlabel existing work.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.labeldefinition')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='annotations.annotationrevision')),
                ('selector', models.ForeignKey(blank=True, help_text='Narrows the target (a frame, a slice). NULL applies to the whole target.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationselector')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationtarget')),
            ],
            options={
                'db_table': 'annotations_spatial_3d_item',
                'ordering': ['revision_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the revision; not semantic.')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Tool-specific extras. Never a place for coordinates or labels.')),
                ('kind', models.CharField(choices=[('length', 'Length'), ('perimeter', 'Perimeter'), ('diameter', 'Diameter'), ('angle', 'Angle'), ('area', 'Area'), ('volume', 'Volume'), ('mean', 'Mean'), ('stddev', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('count', 'Count')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('mm', 'mm'), ('mm2', 'mm²'), ('mm3', 'mm³'), ('px', 'px'), ('px2', 'px²'), ('px3', 'px³'), ('deg', 'degrees'), ('hu', 'HU'), ('none', '(none)')], max_length=8)),
                ('is_calibrated', models.BooleanField(default=False, help_text='True only when a real-world scale was known for the source pixels. False forbids a millimetre unit -- see the check constraint.')),
                ('calibration_note', models.CharField(blank=True, help_text='Where the scale came from: DICOM PixelSpacing, a NIfTI affine, a manual ruler.', max_length=255)),
                ('sample_count', models.PositiveIntegerField(blank=True, help_text='Voxels or pixels behind a statistic; NULL for a geometric measure.', null=True)),
                ('geometry_2d_item', models.ForeignKey(blank=True, help_text='The planar shape this number was computed from, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='annotations.geometry2ditem')),
                ('label', models.ForeignKey(blank=True, help_text='PROTECT: retiring a label must not silently unlabel existing work.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.labeldefinition')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='annotations.annotationrevision')),
                ('selector', models.ForeignKey(blank=True, help_text='Narrows the target (a frame, a slice). NULL applies to the whole target.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationselector')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationtarget')),
                ('spatial_3d_item', models.ForeignKey(blank=True, help_text='The three-space shape this number was computed from, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='annotations.spatialannotation3ditem')),
            ],
            options={
                'db_table': 'annotations_measurement_item',
                'ordering': ['revision_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemporalAnnotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the revision; not semantic.')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Tool-specific extras. Never a place for coordinates or labels.')),
                ('start_time_ms', models.PositiveIntegerField()),
                ('end_time_ms', models.PositiveIntegerField(help_text='Exclusive. Equal to start_time_ms for an instant.')),
                ('label', models.ForeignKey(blank=True, help_text='PROTECT: retiring a label must not silently unlabel existing work.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.labeldefinition')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='annotations.annotationrevision')),
                ('selector', models.ForeignKey(blank=True, help_text='Narrows the target (a frame, a slice). NULL applies to the whole target.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationselector')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='annotations.annotationtarget')),
            ],
            options={
                'db_table': 'annotations_temporal_item',
                'ordering': ['revision_id', 'start_time_ms', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('yggdrasil_json', 'Yggdrasil JSON'), ('cornerstone_state', 'Cornerstone state'), ('nifti_labelmap', 'NIfTI labelmap'), ('dicom_seg', 'DICOM SEG'), ('dicom_rtstruct', 'DICOM RTSTRUCT'), ('dicom_sr', 'DICOM SR'), ('png_render', 'PNG render'), ('npz_mask', 'NPZ mask')], max_length=32)),
                ('canonical_slot', models.PositiveSmallIntegerField(blank=True, default=None, help_text='1 on the canonical payload, NULL on every other. Nullable slot for the same reason as AnnotationTarget.primary_slot (F12).', null=True)),
                ('variant', models.CharField(blank=True, help_text="Distinguishes two payloads of the same format on one revision. The panoramic bakes both a MIP and a ray-sum strip, so 'one png_render per revision' would be wrong; blank where a format occurs once.", max_length=40)),
                ('data', models.JSONField(blank=True, help_text='Inline content for JSON formats; NULL for artifact formats.', null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, help_text='Artifact bytes in object storage; NULL for inline formats.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotation_payloads', to='common.fileregistry')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='annotations.annotationrevision')),
            ],
            options={
                'db_table': 'annotations_annotation_payload',
                'ordering': ['revision_id', 'id'],
                'indexes': [models.Index(fields=['format'], name='annotations_format_1ffd53_idx'), models.Index(fields=['file'], name='annotations_file_id_04bcef_idx')],
                'constraints': [models.UniqueConstraint(fields=('revision', 'canonical_slot'), name='annotations_uniq_payload_canonical_slot'), models.UniqueConstraint(fields=('revision', 'format', 'variant'), name='annotations_uniq_payload_format_variant'), models.CheckConstraint(condition=models.Q(models.Q(('data__isnull', True), ('file__isnull', False)), models.Q(('data__isnull', False), ('file__isnull', True)), _connector='OR'), name='annotations_payload_exactly_one_body')],
            },
        ),
        migrations.AddIndex(
            model_name='annotationrevision',
            index=models.Index(fields=['annotation_set', 'created_at'], name='annotations_annotat_4b0205_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationrevision',
            index=models.Index(fields=['author'], name='annotations_author__1484bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotationrevision',
            constraint=models.UniqueConstraint(fields=('annotation_set', 'revision_number'), name='annotations_uniq_revision_number'),
        ),
        migrations.AddIndex(
            model_name='annotationselector',
            index=models.Index(fields=['target', 'kind'], name='annotations_target__072cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationselector',
            index=models.Index(fields=['target', 'start_time_ms'], name='annotations_target__f9e93b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationselector',
            index=models.Index(fields=['target', 'slice_axis', 'slice_index'], name='annotations_target__525346_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotationselector',
            constraint=models.CheckConstraint(condition=models.Q(('end_time_ms__isnull', True), ('start_time_ms__isnull', True), ('end_time_ms__gte', models.F('start_time_ms')), _connector='OR'), name='annotations_selector_time_span_ordered'),
        ),
        migrations.AddIndex(
            model_name='geometry2ditem',
            index=models.Index(fields=['revision', 'geometry_type'], name='annotations_revisio_40ebba_idx'),
        ),
        migrations.AddIndex(
            model_name='geometry2ditem',
            index=models.Index(fields=['target'], name='annotations_target__3c0d46_idx'),
        ),
        migrations.AddIndex(
            model_name='geometry2ditem',
            index=models.Index(fields=['label'], name='annotations_label_i_9e8312_idx'),
        ),
        migrations.AddIndex(
            model_name='eventannotationitem',
            index=models.Index(fields=['revision', 'event_type'], name='annotations_revisio_cdb225_idx'),
        ),
        migrations.AddIndex(
            model_name='eventannotationitem',
            index=models.Index(fields=['target', 'time_ms'], name='annotations_target__b12850_idx'),
        ),
        migrations.AddIndex(
            model_name='eventannotationitem',
            index=models.Index(fields=['label'], name='annotations_label_i_d438de_idx'),
        ),
        migrations.AddConstraint(
            model_name='labelschema',
            constraint=models.UniqueConstraint(fields=('slug', 'version'), name='annotations_uniq_schema_slug_version'),
        ),
        migrations.AddIndex(
            model_name='labeldefinition',
            index=models.Index(fields=['schema', 'is_active'], name='annotations_schema__d83ced_idx'),
        ),
        migrations.AddConstraint(
            model_name='labeldefinition',
            constraint=models.UniqueConstraint(fields=('schema', 'value'), name='annotations_uniq_label_schema_value'),
        ),
        migrations.AddConstraint(
            model_name='labeldefinition',
            constraint=models.UniqueConstraint(fields=('schema', 'code'), name='annotations_uniq_label_schema_code'),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['domain', 'kind'], name='annotations_domain_c24d92_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['patient', 'kind'], name='annotations_patient_32d100_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['brain_patient', 'kind'], name='annotations_brain_p_d0c3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['laparoscopy_patient', 'kind'], name='annotations_laparos_f4549f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['domain', 'ever_annotated'], name='annotations_domain_b1c465_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceresource',
            index=models.Index(fields=['kind'], name='annotations_kind_9d521d_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceresource',
            index=models.Index(fields=['file', 'file_key'], name='annotations_file_id_a90c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceresource',
            index=models.Index(fields=['series_instance_uid'], name='annotations_series__feaecf_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceresource',
            index=models.Index(fields=['frame_of_reference_uid'], name='annotations_frame_o_2d2fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationtarget',
            index=models.Index(fields=['source_resource'], name='annotations_source__06fb52_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotationtarget',
            constraint=models.UniqueConstraint(fields=('annotation_set', 'primary_slot'), name='annotations_uniq_target_primary_slot'),
        ),
        migrations.AddConstraint(
            model_name='annotationtarget',
            constraint=models.UniqueConstraint(fields=('annotation_set', 'source_resource', 'role'), name='annotations_uniq_target_resource_role'),
        ),
        migrations.AddIndex(
            model_name='spatialannotation3ditem',
            index=models.Index(fields=['revision', 'geometry_type'], name='annotations_revisio_8580e9_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialannotation3ditem',
            index=models.Index(fields=['target'], name='annotations_target__458a77_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialannotation3ditem',
            index=models.Index(fields=['label'], name='annotations_label_i_b9eac5_idx'),
        ),
        migrations.AddIndex(
            model_name='spatialannotation3ditem',
            index=models.Index(fields=['frame_of_reference_uid'], name='annotations_frame_o_e60372_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementitem',
            index=models.Index(fields=['revision', 'kind'], name='annotations_revisio_fed622_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementitem',
            index=models.Index(fields=['geometry_2d_item'], name='annotations_geometr_38135f_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementitem',
            index=models.Index(fields=['spatial_3d_item'], name='annotations_spatial_d48f5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementitem',
            constraint=models.CheckConstraint(condition=models.Q(('is_calibrated', True), models.Q(('unit__in', ['mm', 'mm2', 'mm3']), _negated=True), _connector='OR'), name='annotations_measurement_mm_requires_calibration'),
        ),
        migrations.AddIndex(
            model_name='temporalannotationitem',
            index=models.Index(fields=['revision', 'start_time_ms'], name='annotations_revisio_07a09d_idx'),
        ),
        migrations.AddIndex(
            model_name='temporalannotationitem',
            index=models.Index(fields=['target', 'start_time_ms'], name='annotations_target__02d6a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='temporalannotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_time_ms__gte', models.F('start_time_ms'))), name='annotations_temporal_span_ordered'),
        ),
    ]
