# Generated by Django 5.2.17 on 2026-09-23 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Keep the ('common', '0059_...') edge even if it looks redundant. On a fresh
    # database Django plans the `annotations` leaf first, visiting its dependencies
    # before 0005; 0005 runs `annotations_convert_legacy` against the live models, so
    # the cardiology FK columns on FileRegistry/Job/ProcessingJob must already exist.
    # Never fix that ordering by editing 0005's dependencies: production has 0005
    # applied, and an applied migration gaining an unapplied dependency stops
    # `migrate` with InconsistentMigrationHistory.
    dependencies = [
        ('annotations', '0008_annotationset_urology_patient_and_more'),
        ('brain', '0023_remove_folder_is_demo'),
        ('cardiology', '0001_initial'),
        ('common', '0059_fileregistry_cardiology_patient_and_more'),
        ('laparoscopy', '0015_remove_folder_is_demo'),
        ('maxillo', '0033_remove_folder_is_demo'),
        ('urology', '0003_remove_patient_dataset_remove_folder_is_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationset',
            name='cardiology_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_sets', to='cardiology.patient'),
        ),
        migrations.AlterField(
            model_name='annotationset',
            name='domain',
            field=models.CharField(choices=[('maxillo', 'Maxillo'), ('brain', 'Brain'), ('laparoscopy', 'Laparoscopy'), ('urology', 'Urology'), ('cardiology', 'Cardiology')], default='maxillo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='annotationset',
            index=models.Index(fields=['cardiology_patient', 'kind'], name='annotations_cardiol_0655fb_idx'),
        ),
    ]
