# Generated by Django 5.2.17 on 2026-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_purge_video_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationset',
            name='kind',
            field=models.CharField(choices=[('ios_landmarks', 'IOS landmarks'), ('intraoral_segmentation', 'Intraoral tooth segmentation'), ('occlusion_classification', 'Occlusion classification'), ('study_notes', 'Study notes'), ('panoramic_arch', 'Panoramic arch'), ('video_regions', 'Video region annotation'), ('video_quadrants', 'Video quadrant markers'), ('voice_caption', 'Voice caption'), ('volume_segmentation', 'Volume segmentation'), ('measurements', 'Measurements'), ('ecg_rhythm_classification', 'ECG rhythm classification'), ('image_segmentation', 'Image segmentation (labelmaps)')], max_length=40),
        ),
    ]
