# Generated by Django 5.2.15 on 2026-09-21 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0053_demo_guest_project_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardiologyProject',
            fields=[
            ],
            options={
                'verbose_name': 'Cardiology project',
                'verbose_name_plural': 'Cardiology projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.project',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardiology_folders_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cardiology.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_folders', to='common.project')),
            ],
            options={
                'db_table': 'cardiology_folder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard User'), ('annotator', 'Annotator'), ('project_manager', 'Project Manager')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='cardiology.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_folder_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cardiology_folder_access',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('debug', 'Debug')], default='private', max_length=10)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='cardiology.folder')),
                ('modalities', models.ManyToManyField(blank=True, help_text='Modalities available for this patient', related_name='cardiology_patients', to='common.modality')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_patients', to='common.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardiology_patients_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cardiology_patient',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('classifier', models.CharField(choices=[('manual', 'Manual'), ('pipeline', 'Pipeline')], default='manual', max_length=10)),
                ('value', models.CharField(choices=[('AF', 'AF'), ('NSR', 'NSR'), ('Other', 'Other'), ('NI', 'NI')], max_length=10)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardiology_classifications_authored', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='cardiology.patient')),
            ],
            options={
                'db_table': 'cardiology_classification',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cardiology_tag',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='cardiology__name_f2cd28_idx')],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='cardiology.tag'),
        ),
        migrations.CreateModel(
            name='VoiceCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Duration of audio recording in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(blank=True, default='', max_length=255)),
                ('text_caption', models.TextField(blank=True, null=True)),
                ('original_text_caption', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_captions', to='cardiology.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_voice_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cardiology_voicecaption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Share link expiry; null = never expires', null=True)),
                ('query_params', models.JSONField(default=dict, help_text='Stores folder_ids, artifacts, and filters')),
                ('query_summary', models.CharField(blank=True, help_text='Human-readable query summary', max_length=500)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated ZIP file', max_length=1000)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size of export file in bytes')),
                ('patient_count', models.IntegerField(default=0, help_text='Number of patients in export')),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed')),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('authenticated', 'Any logged-in user'), ('public', 'Anyone with link')], default='private', help_text='Controls who can access the share link', max_length=20)),
                ('share_token', models.CharField(blank=True, help_text='Random token used for share link access', max_length=64, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, help_text='When sharing was last enabled', null=True)),
                ('progress_message', models.CharField(blank=True, help_text='Current phase or progress text', max_length=255)),
                ('progress_percent', models.IntegerField(blank=True, help_text='Progress 0-100', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cardiology_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cardiology__user_id_ec6554_idx'), models.Index(fields=['status', 'created_at'], name='cardiology__status_757f5d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project'], name='cardiology__project_6915d8_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='cardiology__parent__587c67_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='cardiology__name_548627_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['folder'], name='cardiology__folder__8e53b2_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['user'], name='cardiology__user_id_c0f20c_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['role'], name='cardiology__role_7eb48a_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['folder', 'role'], name='cardiology__folder__ece208_idx'),
        ),
        migrations.AddIndex(
            model_name='folderaccess',
            index=models.Index(fields=['user', 'role'], name='cardiology__user_id_d7c7ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderaccess',
            unique_together={('user', 'folder')},
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['patient', 'classifier'], name='cardiology__patient_2f0c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['classifier'], name='cardiology__classif_3f352f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('patient', 'classifier')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility'], name='cardiology__visibil_dc889d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['uploaded_at'], name='cardiology__uploade_300251_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['folder'], name='cardiology__folder__6e8b16_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['project'], name='cardiology__project_19d935_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='cardiology__name_866e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visibility', 'uploaded_at'], name='cardiology__visibil_2c96db_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['patient', 'processing_status'], name='cardiology__patient_04c4de_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['processing_status'], name='cardiology__process_73c402_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecaption',
            index=models.Index(fields=['user'], name='cardiology__user_id_5a885e_idx'),
        ),
    ]
